export type HomeLocale = 'ru' | 'en' | 'zh';

const ru = {
  a11y: { site: 'Прозрачная Цена', nav: 'Главная навигация', menu: 'Меню', controlTower: 'Фрагмент control tower Сделки' },
  nav: { how: 'Как работает', participants: 'Участникам', tai: 'TAI', integrations: 'Интеграции', status: 'Надёжность', login: 'Войти', connect: 'Подключить организацию' },
  hero: { kicker: 'Единый контур агробизнеса', title: 'Единая цифровая инфраструктура исполнения агросделки', lead: 'Платформа связывает цену, участников, логистику, качество, документы, расчёты и доказательства в одном управляемом контуре.', primary: 'Посмотреть сделку в работе', secondary: 'Подключить организацию', tertiary: 'Как работает TAI' },
  tower: { deal: 'Сделка PC-2026-0719', stage: 'Приёмка и качество', statusLabel: 'Статус', status: 'Расчёт заблокирован', deviation: 'Отклонение', ownerLabel: 'Ответственный', owner: 'Лаборатория', deadline: 'До 16:30', moneyLabel: 'Деньги', money: 'Зарезервированы', release: 'Release запрещён', nextLabel: 'Следующий шаг', next: 'Подписать акт', nextNote: 'Затем — правило перерасчёта', taiTitle: 'TAI выявил два блокера', taiText: 'Расхождение качества и отсутствующая подпись. Подготовлен проект действия.' },
  category: { eyebrow: 'Категория продукта', title: 'Не площадка объявлений. Контур исполнения сделки.', text: 'Платформа не заканчивается после выбора цены или контрагента. Она сопровождает фактическое исполнение до расчёта, закрытия и сохранения доказательств.', marketplace: 'Marketplace', marketplaceText: 'Помогает найти предложение и договориться.', platform: 'Прозрачная Цена', platformText: 'Связывает условия, исполнение, качество, документы, деньги и спор вокруг одной Сделки.' },
  lifecycle: { eyebrow: 'Единый контур', title: 'Путь Сделки', lead: 'Каждый этап имеет ответственного, основание завершения, возможный блокер и денежное последствие.', phases: ['Условия', 'Допуск', 'Торги', 'Сделка', 'Договор', 'Финансирование', 'Перевозка', 'Приёмка', 'Качество', 'Документы', 'Госсистемы', 'Деньги', 'Спор', 'Доказательства', 'Закрытие', 'Аналитика'] },
  scenario: { eyebrow: 'Интерактивный сценарий работы платформы', title: 'Разберите исполнение сделки за 90 секунд', lead: 'Партия подсолнечника прибыла на приёмку. Показатель качества отличается от допуска, документ не подписан, выплата зарезервирована.', dealLabel: 'Сделка', dealValue: 'Подсолнечник · 1 200 т', stageLabel: 'Текущий этап', stageValue: 'Приёмка / лаборатория', blockerLabel: 'Блокер', ownerLabel: 'Ответственный', status: 'Расчёт заблокирован', blocker: 'Влажность выше допуска на 0,8 п.п. и отсутствует подпись под актом расхождений.', owner: 'Лаборатория и покупатель', money: 'Средства зарезервированы. Release запрещён до подтверждения основания.', next: 'Следующий шаг: подписать акт и выбрать правило перерасчёта.', evidence: 'Основания: протокол лаборатории, акт приёмки, версия спецификации.' },
  tai: { eyebrow: 'TAI внутри Сделки', title: 'Интеллектуальный операционный слой, а не отдельный чат', text: 'TAI анализирует состояние Сделки, документы и события, объясняет блокировки, показывает риск и помогает подготовить следующий шаг.', mode: 'Операционный режим', answer: 'Сделка не может перейти к окончательному расчёту: лабораторный показатель вышел за допуск, а акт расхождений не подписан покупателем.', modes: ['Публичный — объясняет платформу без закрытых данных', 'Ролевой — работает только в пределах прав пользователя и организации', 'Операционный — анализирует Сделку и готовит действия для подтверждения человеком'], boundaries: 'TAI не меняет роль или организацию, не подписывает документы, не выпускает деньги, не выбирает победителя и не принимает решение по спору.', source: 'Источник: протокол лаборатории № L-204', freshness: 'Актуальность: 22.07.2026', confidence: 'Уверенность: высокая', action: 'Подготовлен проект акта расхождений — требуется подтверждение пользователя.' },
  crops: { eyebrow: 'Охват растениеводства', title: 'Единая логика сделки для товарных категорий растениеводства', lead: 'Для каждой категории платформа связывает спецификацию товара, качество, хранение, перевозку, приёмку, документы и формулу расчёта.', groups: [['Зерновые', 'Партия · качество · СДИЗ'], ['Масличные и бобовые', 'Допуски · лаборатория · перерасчёт'], ['Технические культуры', 'Спецификация · хранение · приёмка'], ['Овощи и картофель', 'Сортность · упаковка · температурный режим'], ['Плодово-ягодная продукция', 'Качество · сроки · холодовая цепь'], ['Семена и посадочный материал', 'Партия · документы · прослеживаемость']] },
  participants: { eyebrow: 'Ценность для участников', title: 'Не список функций, а управляемый результат', cards: [['Продавец', 'Видит, что требуется для оплаты и кто задерживает переход Сделки.'], ['Покупатель', 'Получает связанные подтверждения товара, количества, качества и приёмки.'], ['Логистика', 'Работает с рейсом, документами и отклонениями в одном контуре.'], ['Хранение', 'Фиксирует приёмку, вес, размещение и основания передачи товара.'], ['Лаборатория', 'Передаёт результат с привязкой к партии, пробе и документу.'], ['Банк / compliance', 'Получает события, денежные основания и воспроизводимый audit trail.']] },
  money: { eyebrow: 'Финансовое исполнение', title: 'Деньги связаны с подтверждёнными событиями Сделки', chain: 'Резервирование → исполнение → подтверждение → release → сверка → закрытие', exception: 'При отклонении: блокировка → спор → доказательства → решение → перерасчёт' },
  integrations: { eyebrow: 'Интеграционный контур', title: 'Платформа объединяет данные внешних систем вокруг одной Сделки', items: [['ФГИС «Зерно» / СДИЗ', 'Прослеживаемость партии'], ['ЭДО / КЭП', 'Юридически значимые документы'], ['ГИС ЭПД', 'Перевозочные документы и события'], ['Банковские API', 'Резервирование, выплаты и сверка'], ['ERP / CRM', 'Обмен данными и статусами'], ['Лаборатории / телематика', 'Качество, маршрут и фактические события']] },
  federal: { eyebrow: 'Федеральный класс', title: 'Промышленные принципы платформы', pillars: ['Единая событийная модель Сделки', 'Server-authoritative RBAC', 'Tenant isolation', 'Непрерывный audit trail', 'Горизонтальное масштабирование', 'Интеграционная архитектура'] },
  maturity: { eyebrow: 'Надёжность исполнения', title: 'Контроль встроен в каждый переход Сделки', cards: [['Единый объект', 'Участники, товар, рейс, качество, документы и деньги связаны одной карточкой Сделки.'], ['Управляемые переходы', 'Каждый следующий этап опирается на роль, событие, документ и проверяемое основание.'], ['Доказательная база', 'Версии, действия, отклонения и решения сохраняются в воспроизводимом audit trail.'], ['Безопасные действия', 'Критические операции проходят проверку прав, контекста, идемпотентности и подтверждения.']] },
  faq: { eyebrow: 'Коротко о главном', title: 'Частые вопросы', items: [['Это marketplace?', 'Нет. Поиск условий может быть частью процесса, но ценность платформы — в исполнении Сделки до расчёта и закрытия.'], ['TAI действует самостоятельно?', 'TAI анализирует, объясняет и готовит действия. Критические операции выполняются только в пределах прав и после подтверждения человека.'], ['Как платформа работает с внешними системами?', 'Платформа принимает и передаёт данные через управляемые адаптеры, связывает внешние события со Сделкой и сохраняет единый audit trail.'], ['Платформа работает только с зерном?', 'Нет. Единая модель сделки охватывает товарные категории растениеводства и учитывает различия в качестве, хранении, логистике, документах и расчётах.']] },
  final: { title: 'Подключите организацию к единому контуру Сделки', lead: 'Объедините роли, товар, логистику, качество, документы и расчёты в одном рабочем пространстве.', primary: 'Подключить организацию', secondary: 'Посмотреть сделку в работе' },
  footer: { note: 'Единая цифровая инфраструктура исполнения агросделки: от цены и допуска до расчёта, доказательств и закрытия.', privacy: 'Конфиденциальность', contacts: 'Контакты' }
} as const;

type WidenCopy<T> = T extends string
  ? string
  : T extends readonly (infer Item)[]
    ? readonly WidenCopy<Item>[]
    : T extends object
      ? { -readonly [Key in keyof T]: WidenCopy<T[Key]> }
      : T;

type HomeCopy = WidenCopy<typeof ru>;

const en: HomeCopy = {
  a11y: { site: 'Transparent Price', nav: 'Main navigation', menu: 'Menu', controlTower: 'Deal control tower preview' },
  nav: { how: 'How it works', participants: 'Participants', tai: 'TAI', integrations: 'Integrations', status: 'Reliability', login: 'Sign in', connect: 'Connect organisation' },
  hero: { kicker: 'Unified agribusiness contour', title: 'Unified digital infrastructure for agricultural transaction execution', lead: 'The platform connects price, participants, logistics, quality, documents, settlement and evidence within one managed contour.', primary: 'View the deal in action', secondary: 'Connect organisation', tertiary: 'How TAI works' },
  tower: { deal: 'Deal PC-2026-0719', stage: 'Acceptance and quality', statusLabel: 'Status', status: 'Settlement blocked', deviation: 'Deviation', ownerLabel: 'Owner', owner: 'Laboratory', deadline: 'Due 16:30', moneyLabel: 'Money', money: 'Reserved', release: 'Release prohibited', nextLabel: 'Next action', next: 'Sign the act', nextNote: 'Then apply the price adjustment rule', taiTitle: 'TAI detected two blockers', taiText: 'A quality discrepancy and a missing signature. A prepared action is ready.' },
  category: { eyebrow: 'Product category', title: 'Not a listings marketplace. A deal execution contour.', text: 'The platform does not stop after price or counterparty selection. It manages execution through settlement, closure and retained evidence.', marketplace: 'Marketplace', marketplaceText: 'Helps find an offer and reach an agreement.', platform: 'Transparent Price', platformText: 'Connects terms, execution, quality, documents, money and disputes around one Deal.' },
  lifecycle: { eyebrow: 'Single contour', title: 'Deal lifecycle', lead: 'Every stage has an owner, completion evidence, possible blocker and financial consequence.', phases: ['Terms', 'Admission', 'Trading', 'Deal', 'Contract', 'Financing', 'Transport', 'Acceptance', 'Quality', 'Documents', 'Public systems', 'Money', 'Dispute', 'Evidence', 'Closure', 'Analytics'] },
  scenario: { eyebrow: 'Interactive platform scenario', title: 'Understand execution in 90 seconds', lead: 'A sunflower lot reached acceptance. Quality differs from tolerance, one document is unsigned, and the payout is reserved.', dealLabel: 'Deal', dealValue: 'Sunflower · 1,200 t', stageLabel: 'Current stage', stageValue: 'Acceptance / laboratory', blockerLabel: 'Blocker', ownerLabel: 'Owner', status: 'Settlement blocked', blocker: 'Moisture is 0.8 pp above tolerance and the discrepancy act is unsigned.', owner: 'Laboratory and buyer', money: 'Funds are reserved. Release is prohibited until the basis is confirmed.', next: 'Next action: sign the act and select the price adjustment rule.', evidence: 'Evidence: laboratory protocol, acceptance act, specification version.' },
  tai: { eyebrow: 'TAI inside the Deal', title: 'An operational intelligence layer, not a separate chat', text: 'TAI analyses the Deal state, documents and events, explains blockers, surfaces risk and helps prepare the next action.', mode: 'Operational mode', answer: 'The Deal cannot proceed to final settlement: the laboratory result is outside tolerance and the discrepancy act is unsigned by the buyer.', modes: ['Public — explains the platform without private data', 'Role-based — works only within user and organisation permissions', 'Operational — analyses the Deal and prepares actions for human confirmation'], boundaries: 'TAI cannot change a role or organisation, sign documents, release money, select a winner or decide a dispute.', source: 'Source: laboratory protocol L-204', freshness: 'Current as of 22 July 2026', confidence: 'Confidence: high', action: 'A discrepancy act draft is prepared — user confirmation is required.' },
  crops: { eyebrow: 'Crop coverage', title: 'One transaction logic for crop categories', lead: 'For every category, the platform connects product specification, quality, storage, transport, acceptance, documents and settlement rules.', groups: [['Grains', 'Lot · quality · traceability'], ['Oilseeds and pulses', 'Tolerances · laboratory · recalculation'], ['Industrial crops', 'Specification · storage · acceptance'], ['Vegetables and potatoes', 'Grade · packaging · temperature'], ['Fruit and berries', 'Quality · timing · cold chain'], ['Seeds and planting material', 'Lot · documents · traceability']] },
  participants: { eyebrow: 'Participant value', title: 'Managed outcomes instead of a feature list', cards: [['Seller', 'Sees what is required for payment and who is delaying the Deal transition.'], ['Buyer', 'Receives linked evidence of product, quantity, quality and acceptance.'], ['Logistics', 'Works with the trip, documents and deviations in one contour.'], ['Storage', 'Records acceptance, weight, placement and transfer grounds.'], ['Laboratory', 'Submits results linked to the lot, sample and document.'], ['Bank / compliance', 'Receives events, payment grounds and a reproducible audit trail.']] },
  money: { eyebrow: 'Financial execution', title: 'Money is linked to confirmed Deal events', chain: 'Reservation → execution → confirmation → release → reconciliation → closure', exception: 'On deviation: block → dispute → evidence → decision → recalculation' },
  integrations: { eyebrow: 'Integration contour', title: 'The platform connects external-system data around one Deal', items: [['FGIS Grain / SDIZ', 'Lot traceability'], ['EDI / digital signature', 'Legally significant documents'], ['GIS EPD', 'Transport documents and events'], ['Bank APIs', 'Reservation, payouts and reconciliation'], ['ERP / CRM', 'Data and status exchange'], ['Laboratories / telematics', 'Quality, route and actual events']] },
  federal: { eyebrow: 'Federal class', title: 'Industrial platform principles', pillars: ['Unified Deal event model', 'Server-authoritative RBAC', 'Tenant isolation', 'Continuous audit trail', 'Horizontal scaling', 'Integration architecture'] },
  maturity: { eyebrow: 'Execution reliability', title: 'Control is embedded in every Deal transition', cards: [['Single object', 'Participants, product, trip, quality, documents and money are linked to one Deal record.'], ['Governed transitions', 'Every next stage relies on a role, event, document and verifiable basis.'], ['Evidence chain', 'Versions, actions, deviations and decisions remain in a reproducible audit trail.'], ['Safe actions', 'Critical operations pass permission, context, idempotency and confirmation checks.']] },
  faq: { eyebrow: 'Key answers', title: 'Frequently asked questions', items: [['Is this a marketplace?', 'No. Finding terms may be part of the process, but the platform value is Deal execution through settlement and closure.'], ['Does TAI act autonomously?', 'TAI analyses, explains and prepares actions. Critical operations execute only within permissions and after human confirmation.'], ['How does the platform work with external systems?', 'The platform exchanges data through governed adapters, links external events to the Deal and retains one audit trail.'], ['Is the platform only for grain?', 'No. The unified Deal model covers crop categories and accounts for differences in quality, storage, logistics, documents and settlement.']] },
  final: { title: 'Connect your organisation to the Deal execution contour', lead: 'Unify roles, product, logistics, quality, documents and settlement in one operational workspace.', primary: 'Connect organisation', secondary: 'View the deal in action' },
  footer: { note: 'Unified digital infrastructure for agricultural transaction execution: from price and admission to settlement, evidence and closure.', privacy: 'Privacy', contacts: 'Contacts' }
};

const zh: HomeCopy = {
  a11y: { site: '透明价格', nav: '主导航', menu: '菜单', controlTower: '交易控制塔预览' },
  nav: { how: '工作方式', participants: '参与方', tai: 'TAI', integrations: '集成', status: '可靠性', login: '登录', connect: '接入机构' },
  hero: { kicker: '统一农业业务链路', title: '农业交易执行的一体化数字基础设施', lead: '平台在同一可管理链路中连接价格、参与方、物流、质量、文件、结算与证据。', primary: '查看交易运行', secondary: '接入机构', tertiary: 'TAI 如何工作' },
  tower: { deal: '交易 PC-2026-0719', stage: '验收与质量', statusLabel: '状态', status: '结算已阻塞', deviation: '偏差', ownerLabel: '责任方', owner: '实验室', deadline: '截止 16:30', moneyLabel: '资金', money: '已预留', release: '禁止放款', nextLabel: '下一步', next: '签署差异单', nextNote: '随后应用价格调整规则', taiTitle: 'TAI 识别出两个阻塞项', taiText: '质量偏差和缺少签名。已准备待确认操作。' },
  category: { eyebrow: '产品类别', title: '不是信息发布平台，而是交易执行链路。', text: '平台不会在价格或交易对手确定后结束，而是持续管理执行、结算、关闭和证据留存。', marketplace: '信息平台', marketplaceText: '帮助寻找报价并达成意向。', platform: '透明价格', platformText: '围绕同一笔交易连接条件、执行、质量、文件、资金和争议。' },
  lifecycle: { eyebrow: '统一链路', title: '交易路径', lead: '每个阶段都有责任人、完成依据、潜在阻塞项和资金影响。', phases: ['条件', '准入', '交易', '成交', '合同', '融资', '运输', '验收', '质量', '文件', '政府系统', '资金', '争议', '证据', '关闭', '分析'] },
  scenario: { eyebrow: '平台交互场景', title: '90 秒理解交易执行', lead: '一批葵花籽到达验收点。质量指标超出容差，一份文件未签署，款项已预留。', dealLabel: '交易', dealValue: '葵花籽 · 1,200 吨', stageLabel: '当前阶段', stageValue: '验收 / 实验室', blockerLabel: '阻塞项', ownerLabel: '责任方', status: '结算已阻塞', blocker: '水分高于容差 0.8 个百分点，差异单尚未签署。', owner: '实验室和买方', money: '资金已预留。在依据确认前禁止放款。', next: '下一步：签署差异单并选择价格调整规则。', evidence: '依据：实验室报告、验收单和规格版本。' },
  tai: { eyebrow: '交易中的 TAI', title: '内置运营智能层，而不是独立聊天窗口', text: 'TAI 分析交易状态、文件和事件，解释阻塞项，提示风险并协助准备下一步操作。', mode: '运营模式', answer: '该交易无法进入最终结算：实验室指标超出容差，且买方尚未签署差异单。', modes: ['公开模式——在不访问私有数据的情况下解释平台', '角色模式——仅在用户和机构权限范围内工作', '运营模式——分析交易并准备由人工确认的操作'], boundaries: 'TAI 不可更改角色或机构、签署文件、释放资金、选择获胜方或裁决争议。', source: '来源：实验室报告 L-204', freshness: '数据截至 2026 年 7 月 22 日', confidence: '置信度：高', action: '已准备差异单草稿——需要用户确认。' },
  crops: { eyebrow: '种植业覆盖', title: '面向不同种植业品类的统一交易逻辑', lead: '平台为每个品类连接商品规格、质量、仓储、运输、验收、文件与结算规则。', groups: [['谷物', '批次 · 质量 · 追溯'], ['油料和豆类', '容差 · 实验室 · 重算'], ['工业作物', '规格 · 仓储 · 验收'], ['蔬菜和马铃薯', '等级 · 包装 · 温控'], ['水果和浆果', '质量 · 时效 · 冷链'], ['种子和种植材料', '批次 · 文件 · 追溯']] },
  participants: { eyebrow: '参与方价值', title: '展示可管理的结果，而不是功能清单', cards: [['卖方', '查看收款所需条件以及哪一方正在延迟交易流转。'], ['买方', '获得商品、数量、质量和验收的关联证明。'], ['物流', '在同一链路中处理运输任务、文件和偏差。'], ['仓储', '记录验收、重量、存放和交接依据。'], ['实验室', '提交与批次、样品和文件关联的结果。'], ['银行 / 合规', '获得事件、付款依据和可复现的审计轨迹。']] },
  money: { eyebrow: '资金执行', title: '资金与已确认的交易事件关联', chain: '预留 → 执行 → 确认 → 放款 → 对账 → 关闭', exception: '发生偏差时：阻塞 → 争议 → 证据 → 决定 → 重新计算' },
  integrations: { eyebrow: '集成链路', title: '平台围绕同一笔交易连接外部系统数据', items: [['ФГИС“谷物”/ СДИЗ', '批次追溯'], ['电子文件 / 数字签名', '具有法律效力的文件'], ['ГИС ЭПД', '运输文件与事件'], ['银行 API', '预留、付款与对账'], ['ERP / CRM', '数据与状态交换'], ['实验室 / 车联网', '质量、路线与实际事件']] },
  federal: { eyebrow: '联邦级', title: '工业级平台原则', pillars: ['统一交易事件模型', '服务器权威 RBAC', '租户隔离', '连续审计轨迹', '横向扩展', '集成架构'] },
  maturity: { eyebrow: '执行可靠性', title: '控制嵌入每一次交易流转', cards: [['统一对象', '参与方、商品、运输、质量、文件和资金均关联到同一笔交易。'], ['受控流转', '每个下一阶段都基于角色、事件、文件和可验证依据。'], ['证据链', '版本、操作、偏差和决定保留在可复现的审计轨迹中。'], ['安全操作', '关键操作经过权限、上下文、幂等性和确认检查。']] },
  faq: { eyebrow: '核心问题', title: '常见问题', items: [['这是信息市场吗？', '不是。寻找条件可以是流程的一部分，但平台价值在于交易执行直到结算和关闭。'], ['TAI 会自主操作吗？', 'TAI 负责分析、解释和准备操作；关键操作仅在权限范围内并经人工确认后执行。'], ['平台如何与外部系统协同？', '平台通过受控适配器交换数据，将外部事件关联到交易，并保留统一审计轨迹。'], ['平台只适用于谷物吗？', '不是。统一交易模型覆盖种植业品类，并处理质量、仓储、物流、文件和结算方面的差异。']] },
  final: { title: '将机构接入统一交易执行链路', lead: '在同一工作空间中统一角色、商品、物流、质量、文件与结算。', primary: '接入机构', secondary: '查看交易运行' },
  footer: { note: '农业交易执行的一体化数字基础设施：从价格和准入到结算、证据与关闭。', privacy: '隐私', contacts: '联系方式' }
};

export function getPlatformV7HomeCopy(locale: string): HomeCopy {
  return locale === 'en' ? en : locale === 'zh' ? zh : ru;
}
