export type HomeLocale = 'ru' | 'en' | 'zh';

const ru = {
  a11y: { site: 'Прозрачная Цена', nav: 'Главная навигация', menu: 'Меню', controlTower: 'Карточка текущего состояния Сделки' },
  nav: { how: 'Как работает', participants: 'Участникам', tai: 'TAI', integrations: 'Интеграции', status: 'Надёжность', login: 'Войти', connect: 'Подключить организацию' },
  hero: { kicker: 'Цифровая инфраструктура растениеводства', title: 'Вся агросделка — от цены до закрытия', lead: 'Платформа связывает условия, участников, торги, логистику, качество, документы, расчёты и доказательства вокруг одной Сделки.', primary: 'Посмотреть, как проходит Сделка', secondary: 'Подключить организацию', tertiary: 'Что делает TAI' },
  tower: { deal: 'Сделка PC-2026-0719', stage: 'Приёмка и качество', statusLabel: 'Статус', status: 'Расчёт остановлен', deviation: 'Есть отклонение', ownerLabel: 'Ответственный', owner: 'Лаборатория', deadline: 'До 16:30', moneyLabel: 'Деньги', money: 'Зарезервированы', release: 'Выплата остановлена', nextLabel: 'Следующий шаг', next: 'Подписать акт', nextNote: 'Затем применить правило перерасчёта', taiTitle: 'TAI нашёл две причины остановки', taiText: 'Качество не совпало с условиями, акт не подписан. Проект следующего действия готов.' },
  category: { eyebrow: 'Главное отличие', title: 'Не просто поиск цены. Платформа ведёт Сделку до закрытия.', text: 'После выбора условий и контрагента работа только начинается. Платформа связывает фактическое исполнение, расчёты, спор и доказательства до полного закрытия Сделки.', marketplace: 'Площадка объявлений', marketplaceText: 'Помогает найти предложение и договориться.', platform: 'Прозрачная Цена', platformText: 'Связывает условия, исполнение, качество, документы, деньги и спор вокруг одной Сделки.' },
  lifecycle: { eyebrow: 'Этапы Сделки', title: 'Как проходит Сделка', lead: 'На каждом этапе видно, кто отвечает, что должно быть подтверждено, что остановило движение и как это влияет на расчёт.', phases: ['Условия', 'Допуск', 'Торги', 'Сделка', 'Договор', 'Финансирование', 'Перевозка', 'Приёмка', 'Качество', 'Документы', 'Госсистемы', 'Деньги', 'Спор', 'Доказательства', 'Закрытие', 'Аналитика'] },
  scenario: { eyebrow: 'Сделка при отклонении', title: 'Посмотрите, что происходит, если качество не совпало', lead: 'Партия подсолнечника прибыла на приёмку. Влажность выше согласованного допуска, акт не подписан, деньги зарезервированы.', dealLabel: 'Сделка', dealValue: 'Подсолнечник · 1 200 т', stageLabel: 'Текущий этап', stageValue: 'Приёмка и лаборатория', blockerLabel: 'Причина остановки', ownerLabel: 'Ответственный', status: 'Расчёт остановлен', blocker: 'Влажность выше допуска на 0,8 п.п., подписи покупателя под актом расхождений нет.', owner: 'Лаборатория и покупатель', money: 'Деньги зарезервированы. Выплата остановлена до подтверждения основания.', next: 'Следующий шаг: подписать акт и выбрать правило перерасчёта.', evidence: 'Основания: протокол лаборатории, акт приёмки и версия спецификации.' },
  tai: { eyebrow: 'TAI — помощник внутри Сделки', title: 'Показывает проблему и готовит следующий шаг', text: 'TAI собирает статус Сделки, документы и события в короткое объяснение: что остановилось, почему, кто отвечает и что нужно подтвердить.', mode: 'Помощник по Сделке', answer: 'Окончательный расчёт остановлен: влажность выше согласованного допуска, а покупатель ещё не подписал акт расхождений.', modes: ['На публичной странице — отвечает без доступа к закрытым данным', 'В личном кабинете — учитывает роль и права организации', 'В Сделке — анализирует документы и готовит действие для подтверждения'], boundaries: 'TAI не меняет права, не подписывает документы, не выпускает деньги, не выбирает победителя и не решает спор вместо человека.', source: 'Основание: протокол лаборатории № L-204', freshness: 'Данные на 22.07.2026', confidence: 'Надёжность вывода: высокая', action: 'Проект акта расхождений подготовлен и ждёт подтверждения пользователя.' },
  crops: { eyebrow: 'Охват растениеводства', title: 'Одна платформа для разных категорий растениеводства', lead: 'Для каждой категории учитываются свои требования к товару, качеству, хранению, перевозке, приёмке, документам и расчётам.', groups: [['Зерновые', 'Партия · качество · СДИЗ'], ['Масличные и бобовые', 'Допуски · лаборатория · перерасчёт'], ['Технические культуры', 'Спецификация · хранение · приёмка'], ['Овощи и картофель', 'Сортность · упаковка · температурный режим'], ['Плодово-ягодная продукция', 'Качество · сроки · холодовая цепь'], ['Семена и посадочный материал', 'Партия · документы · прослеживаемость']] },
  participants: { eyebrow: 'Для участников', title: 'Каждый участник видит свою часть Сделки', cards: [['Продавец', 'Видит, что осталось подтвердить для оплаты и кто отвечает за следующий шаг.'], ['Покупатель', 'Получает связанные подтверждения товара, количества, качества и приёмки.'], ['Логистика', 'Видит рейс, документы, сроки и отклонения по конкретной Сделке.'], ['Хранение', 'Фиксирует приёмку, вес, размещение и передачу товара.'], ['Лаборатория', 'Передаёт результат с привязкой к партии, пробе и документу.'], ['Банк и контроль', 'Получают события Сделки, основания для расчёта и историю действий.']] },
  money: { eyebrow: 'Расчёты', title: 'Расчёты зависят от подтверждённых событий Сделки', chain: 'Резервирование → исполнение → подтверждение → выплата → сверка → закрытие', exception: 'При отклонении: остановка → спор → доказательства → решение → перерасчёт' },
  integrations: { eyebrow: 'Внешние системы', title: 'Данные внешних систем связываются с конкретной Сделкой', items: [['ФГИС «Зерно» / СДИЗ', 'Партия и прослеживаемость'], ['ЭДО / КЭП', 'Подписание и обмен документами'], ['ГИС ЭПД', 'Перевозочные документы и события'], ['Банковские API', 'Резервирование, выплаты и сверка'], ['ERP / CRM', 'Данные и статусы'], ['Лаборатории / телематика', 'Качество, маршрут и фактические события']] },
  federal: { eyebrow: 'Федеральный масштаб', title: 'Платформа рассчитана на промышленную эксплуатацию', pillars: ['Единые правила для всех этапов Сделки', 'Права и доступ определяются сервером', 'Данные организаций изолированы', 'Все действия фиксируются', 'Нагрузка распределяется между узлами', 'Интеграции подключаются через API'] },
  maturity: { eyebrow: 'Контроль исполнения', title: 'Сделка не переходит дальше без подтверждённого основания', cards: [['Одна карточка Сделки', 'Товар, участники, рейс, качество, документы и деньги связаны между собой.'], ['Проверяемые переходы', 'Каждый следующий этап опирается на роль, событие и документ.'], ['История доказательств', 'Версии, действия, отклонения и решения сохраняются вместе со Сделкой.'], ['Защищённые действия', 'Критические операции проверяют права, контекст и повторный запрос.']] },
  faq: { eyebrow: 'Коротко о главном', title: 'Частые вопросы', items: [['Это площадка объявлений?', 'Нет. Поиск условий может быть частью процесса, но основная работа платформы — вести Сделку до расчёта и закрытия.'], ['TAI действует самостоятельно?', 'TAI анализирует, объясняет и готовит действия. Критические операции выполняются только после проверки прав и подтверждения человека.'], ['Как платформа работает с внешними системами?', 'Платформа обменивается данными через API, связывает внешние события со Сделкой и сохраняет историю действий.'], ['Платформа работает только с зерном?', 'Нет. Единая модель Сделки охватывает категории растениеводства и учитывает различия в качестве, хранении, логистике, документах и расчётах.']] },
  final: { title: 'Подключите организацию к исполнению Сделок', lead: 'Свяжите участников, товар, логистику, качество, документы и расчёты в одной системе.', primary: 'Подключить организацию', secondary: 'Посмотреть, как проходит Сделка' },
  footer: { note: 'Цифровая инфраструктура исполнения агросделки: от условий и торгов до расчёта, доказательств и закрытия.', privacy: 'Конфиденциальность', contacts: 'Контакты' }
} as const;

type WidenCopy<T> = T extends string
  ? string
  : T extends readonly (infer Item)[]
    ? readonly WidenCopy<Item>[]
    : T extends object
      ? { -readonly [Key in keyof T]: WidenCopy<T[Key]> }
      : T;

type HomeCopy = WidenCopy<typeof ru>;

const en: HomeCopy = {
  a11y: { site: 'Transparent Price', nav: 'Main navigation', menu: 'Menu', controlTower: 'Current Deal status card' },
  nav: { how: 'How it works', participants: 'Participants', tai: 'TAI', integrations: 'Integrations', status: 'Reliability', login: 'Sign in', connect: 'Connect organisation' },
  hero: { kicker: 'Digital infrastructure for crop trade', title: 'The whole agricultural deal, from price to closure', lead: 'The platform connects terms, participants, trading, logistics, quality, documents, settlement and evidence around one Deal.', primary: 'See how a Deal works', secondary: 'Connect organisation', tertiary: 'What TAI does' },
  tower: { deal: 'Deal PC-2026-0719', stage: 'Acceptance and quality', statusLabel: 'Status', status: 'Settlement paused', deviation: 'Deviation found', ownerLabel: 'Owner', owner: 'Laboratory', deadline: 'Due 16:30', moneyLabel: 'Money', money: 'Reserved', release: 'Payout paused', nextLabel: 'Next action', next: 'Sign the discrepancy act', nextNote: 'Then apply the price adjustment rule', taiTitle: 'TAI found two reasons for the pause', taiText: 'Quality differs from the terms and the act is unsigned. The next action is prepared.' },
  category: { eyebrow: 'Key difference', title: 'More than price discovery. The platform carries the Deal to closure.', text: 'Work starts after terms and the counterparty are selected. The platform connects physical execution, settlement, disputes and evidence until the Deal is closed.', marketplace: 'Listings marketplace', marketplaceText: 'Helps find an offer and reach an agreement.', platform: 'Transparent Price', platformText: 'Connects terms, execution, quality, documents, money and disputes around one Deal.' },
  lifecycle: { eyebrow: 'Deal stages', title: 'How a Deal progresses', lead: 'At every stage, users can see who is responsible, what must be confirmed, what stopped progress and how it affects settlement.', phases: ['Terms', 'Admission', 'Trading', 'Deal', 'Contract', 'Financing', 'Transport', 'Acceptance', 'Quality', 'Documents', 'Public systems', 'Money', 'Dispute', 'Evidence', 'Closure', 'Analytics'] },
  scenario: { eyebrow: 'Deal with a deviation', title: 'See what happens when quality differs from the agreed terms', lead: 'A sunflower lot reached acceptance. Moisture is above the agreed tolerance, the act is unsigned and funds are reserved.', dealLabel: 'Deal', dealValue: 'Sunflower · 1,200 t', stageLabel: 'Current stage', stageValue: 'Acceptance and laboratory', blockerLabel: 'Reason for pause', ownerLabel: 'Owner', status: 'Settlement paused', blocker: 'Moisture is 0.8 pp above tolerance and the buyer has not signed the discrepancy act.', owner: 'Laboratory and buyer', money: 'Funds are reserved. Payout is paused until the basis is confirmed.', next: 'Next action: sign the act and select the price adjustment rule.', evidence: 'Evidence: laboratory protocol, acceptance act and specification version.' },
  tai: { eyebrow: 'TAI — assistant inside the Deal', title: 'Explains the issue and prepares the next action', text: 'TAI turns Deal status, documents and events into a short answer: what stopped, why, who is responsible and what must be confirmed.', mode: 'Deal assistant', answer: 'Final settlement is paused: moisture is above the agreed tolerance and the buyer has not signed the discrepancy act.', modes: ['On public pages — answers without access to private data', 'In the workspace — follows the user role and organisation permissions', 'Inside the Deal — analyses documents and prepares an action for confirmation'], boundaries: 'TAI cannot change permissions, sign documents, release money, select a winner or decide a dispute instead of a person.', source: 'Basis: laboratory protocol L-204', freshness: 'Data as of 22 July 2026', confidence: 'Conclusion reliability: high', action: 'The discrepancy act draft is ready and awaits user confirmation.' },
  crops: { eyebrow: 'Crop coverage', title: 'One platform for different crop categories', lead: 'Each category keeps its own rules for product, quality, storage, transport, acceptance, documents and settlement.', groups: [['Grains', 'Lot · quality · traceability'], ['Oilseeds and pulses', 'Tolerances · laboratory · recalculation'], ['Industrial crops', 'Specification · storage · acceptance'], ['Vegetables and potatoes', 'Grade · packaging · temperature'], ['Fruit and berries', 'Quality · timing · cold chain'], ['Seeds and planting material', 'Lot · documents · traceability']] },
  participants: { eyebrow: 'For participants', title: 'Every participant sees their part of the Deal', cards: [['Seller', 'Sees what remains to be confirmed for payment and who owns the next action.'], ['Buyer', 'Receives linked evidence of product, quantity, quality and acceptance.'], ['Logistics', 'Sees the trip, documents, timing and deviations for the specific Deal.'], ['Storage', 'Records acceptance, weight, placement and transfer of the product.'], ['Laboratory', 'Submits a result linked to the lot, sample and document.'], ['Bank and control', 'Receive Deal events, settlement grounds and the action history.']] },
  money: { eyebrow: 'Settlement', title: 'Settlement follows confirmed Deal events', chain: 'Reservation → execution → confirmation → payout → reconciliation → closure', exception: 'On deviation: pause → dispute → evidence → decision → recalculation' },
  integrations: { eyebrow: 'External systems', title: 'External-system data is linked to the specific Deal', items: [['FGIS Grain / SDIZ', 'Lot and traceability'], ['EDI / digital signature', 'Document exchange and signing'], ['GIS EPD', 'Transport documents and events'], ['Bank APIs', 'Reservation, payouts and reconciliation'], ['ERP / CRM', 'Data and statuses'], ['Laboratories / telematics', 'Quality, route and actual events']] },
  federal: { eyebrow: 'Federal scale', title: 'Built for industrial operation', pillars: ['One rule set for every Deal stage', 'Permissions are enforced by the server', 'Organisation data is isolated', 'Every action is recorded', 'Load is distributed across nodes', 'Integrations connect through APIs'] },
  maturity: { eyebrow: 'Execution control', title: 'A Deal cannot advance without a confirmed basis', cards: [['One Deal record', 'Product, participants, trip, quality, documents and money remain connected.'], ['Verifiable transitions', 'Every next stage relies on a role, event and document.'], ['Evidence history', 'Versions, actions, deviations and decisions stay with the Deal.'], ['Protected actions', 'Critical operations check permissions, context and repeated requests.']] },
  faq: { eyebrow: 'Key answers', title: 'Frequently asked questions', items: [['Is this a listings marketplace?', 'No. Finding terms may be part of the process, but the platform carries the Deal through settlement and closure.'], ['Does TAI act autonomously?', 'TAI analyses, explains and prepares actions. Critical operations execute only after permission checks and human confirmation.'], ['How does the platform work with external systems?', 'The platform exchanges data through APIs, links external events to the Deal and keeps the action history.'], ['Is the platform only for grain?', 'No. The unified Deal model covers crop categories and accounts for differences in quality, storage, logistics, documents and settlement.']] },
  final: { title: 'Connect your organisation to Deal execution', lead: 'Connect participants, product, logistics, quality, documents and settlement in one system.', primary: 'Connect organisation', secondary: 'See how a Deal works' },
  footer: { note: 'Digital infrastructure for agricultural Deal execution: from terms and trading to settlement, evidence and closure.', privacy: 'Privacy', contacts: 'Contacts' }
};

const zh: HomeCopy = {
  a11y: { site: '透明价格', nav: '主导航', menu: '菜单', controlTower: '当前交易状态卡片' },
  nav: { how: '工作方式', participants: '参与方', tai: 'TAI', integrations: '集成', status: '可靠性', login: '登录', connect: '接入机构' },
  hero: { kicker: '种植业交易数字基础设施', title: '贯通农业交易从定价到关闭的全过程', lead: '平台围绕同一笔交易连接条件、参与方、交易、物流、质量、文件、结算与证据。', primary: '查看交易如何运行', secondary: '接入机构', tertiary: 'TAI 能做什么' },
  tower: { deal: '交易 PC-2026-0719', stage: '验收与质量', statusLabel: '状态', status: '结算已暂停', deviation: '发现偏差', ownerLabel: '责任方', owner: '实验室', deadline: '截止 16:30', moneyLabel: '资金', money: '已预留', release: '付款已暂停', nextLabel: '下一步', next: '签署差异单', nextNote: '随后应用价格调整规则', taiTitle: 'TAI 找到两个暂停原因', taiText: '质量与约定不符，且差异单未签署。下一步操作已准备。' },
  category: { eyebrow: '核心区别', title: '不仅寻找价格，平台还将交易推进到关闭。', text: '条件和交易对手确定后，真正的执行才开始。平台将实物履约、结算、争议和证据一直连接到交易关闭。', marketplace: '信息发布平台', marketplaceText: '帮助寻找报价并达成意向。', platform: '透明价格', platformText: '围绕同一笔交易连接条件、执行、质量、文件、资金和争议。' },
  lifecycle: { eyebrow: '交易阶段', title: '交易如何推进', lead: '每个阶段都能看到责任方、待确认事项、暂停原因以及对结算的影响。', phases: ['条件', '准入', '交易', '成交', '合同', '融资', '运输', '验收', '质量', '文件', '政府系统', '资金', '争议', '证据', '关闭', '分析'] },
  scenario: { eyebrow: '发生偏差的交易', title: '查看质量与约定不一致时平台如何处理', lead: '一批葵花籽到达验收点。水分高于约定容差，差异单未签署，资金已预留。', dealLabel: '交易', dealValue: '葵花籽 · 1,200 吨', stageLabel: '当前阶段', stageValue: '验收与实验室', blockerLabel: '暂停原因', ownerLabel: '责任方', status: '结算已暂停', blocker: '水分高于容差 0.8 个百分点，买方尚未签署差异单。', owner: '实验室和买方', money: '资金已预留。在依据确认前暂停付款。', next: '下一步：签署差异单并选择价格调整规则。', evidence: '依据：实验室报告、验收单和规格版本。' },
  tai: { eyebrow: 'TAI——交易内助手', title: '解释问题并准备下一步操作', text: 'TAI 将交易状态、文件和事件整理成简明结论：哪里停止、为什么、谁负责以及需要确认什么。', mode: '交易助手', answer: '最终结算已暂停：水分高于约定容差，且买方尚未签署差异单。', modes: ['在公开页面——不访问私有数据即可回答', '在工作区——遵循用户角色和机构权限', '在交易中——分析文件并准备待确认操作'], boundaries: 'TAI 不会更改权限、签署文件、释放资金、选择获胜方或替代人工裁决争议。', source: '依据：实验室报告 L-204', freshness: '数据截至 2026 年 7 月 22 日', confidence: '结论可靠性：高', action: '差异单草稿已准备，等待用户确认。' },
  crops: { eyebrow: '种植业覆盖', title: '一个平台覆盖不同种植业品类', lead: '每个品类保留各自的商品、质量、仓储、运输、验收、文件和结算规则。', groups: [['谷物', '批次 · 质量 · 追溯'], ['油料和豆类', '容差 · 实验室 · 重算'], ['工业作物', '规格 · 仓储 · 验收'], ['蔬菜和马铃薯', '等级 · 包装 · 温控'], ['水果和浆果', '质量 · 时效 · 冷链'], ['种子和种植材料', '批次 · 文件 · 追溯']] },
  participants: { eyebrow: '面向参与方', title: '每个参与方都能看到自己负责的交易部分', cards: [['卖方', '查看收款前还需确认什么，以及下一步由谁负责。'], ['买方', '获得商品、数量、质量和验收的关联证明。'], ['物流', '查看具体交易的运输任务、文件、时限和偏差。'], ['仓储', '记录验收、重量、存放和货物交接。'], ['实验室', '提交与批次、样品和文件关联的结果。'], ['银行与控制', '接收交易事件、结算依据和操作历史。']] },
  money: { eyebrow: '结算', title: '结算取决于已确认的交易事件', chain: '预留 → 执行 → 确认 → 付款 → 对账 → 关闭', exception: '发生偏差时：暂停 → 争议 → 证据 → 决定 → 重新计算' },
  integrations: { eyebrow: '外部系统', title: '外部系统数据与具体交易关联', items: [['ФГИС“谷物”/ СДИЗ', '批次与追溯'], ['电子文件 / 数字签名', '文件交换与签署'], ['ГИС ЭПД', '运输文件与事件'], ['银行 API', '预留、付款与对账'], ['ERP / CRM', '数据与状态'], ['实验室 / 车联网', '质量、路线与实际事件']] },
  federal: { eyebrow: '联邦级规模', title: '面向工业化运行设计', pillars: ['所有交易阶段采用统一规则', '权限由服务器执行', '机构数据相互隔离', '所有操作均被记录', '负载可在多个节点间分配', '通过 API 连接外部系统'] },
  maturity: { eyebrow: '执行控制', title: '没有已确认依据，交易不会进入下一阶段', cards: [['一张交易卡片', '商品、参与方、运输、质量、文件和资金保持关联。'], ['可核验流转', '每个下一阶段都基于角色、事件和文件。'], ['证据历史', '版本、操作、偏差和决定随交易保存。'], ['受保护操作', '关键操作会检查权限、上下文和重复请求。']] },
  faq: { eyebrow: '核心问题', title: '常见问题', items: [['这是信息发布平台吗？', '不是。寻找条件可以是流程的一部分，但平台会将交易推进到结算和关闭。'], ['TAI 会自主操作吗？', 'TAI 负责分析、解释和准备操作；关键操作仅在权限检查和人工确认后执行。'], ['平台如何与外部系统协同？', '平台通过 API 交换数据，将外部事件关联到交易，并保留操作历史。'], ['平台只适用于谷物吗？', '不是。统一交易模型覆盖种植业品类，并处理质量、仓储、物流、文件和结算方面的差异。']] },
  final: { title: '将机构接入交易执行', lead: '在一个系统中连接参与方、商品、物流、质量、文件与结算。', primary: '接入机构', secondary: '查看交易如何运行' },
  footer: { note: '农业交易执行数字基础设施：从条件和交易到结算、证据与关闭。', privacy: '隐私', contacts: '联系方式' }
};

export function getPlatformV7HomeCopy(locale: string): HomeCopy {
  return locale === 'en' ? en : locale === 'zh' ? zh : ru;
}
