#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BASE_SCRIPT="$ROOT_DIR/scripts/release/production-like-kubernetes-outbox-runtime-base.sh"
NAMESPACE="grainflow-acceptance"
DEFAULT_INSTALLED=0

if [[ ! -x "$BASE_SCRIPT" ]]; then
  echo "Missing executable base runtime acceptance script: $BASE_SCRIPT" >&2
  exit 2
fi

postgres_password="$(
  kubectl get secret grainflow-postgresql-secrets -n "$NAMESPACE" \
    -o jsonpath='{.data.POSTGRES_PASSWORD}' | base64 -d
)"
printf '::add-mask::%s\n' "$postgres_password"

admin_sql() {
  local sql="$1"
  kubectl exec -n "$NAMESPACE" statefulset/postgresql -- \
    env PGPASSWORD="$postgres_password" \
    psql -v ON_ERROR_STOP=1 -U postgres -d grainflow -Atc "$sql"
}

remove_synthetic_seed_default() {
  if [[ "$DEFAULT_INSTALLED" = "1" ]]; then
    admin_sql 'ALTER TABLE "outbox_entries" ALTER COLUMN "id" DROP DEFAULT;' >/dev/null || true
  fi
}
trap remove_synthetic_seed_default EXIT

# Prisma's cuid() default is generated by Prisma Client, not PostgreSQL. The
# deep-runtime harness seeds synthetic rows through raw SQL, so it installs a
# disposable DB-side UUID default only for the duration of this acceptance run.
# Production schema and application ID semantics remain unchanged.
admin_sql "SELECT gen_random_uuid()::text;" >/dev/null
admin_sql 'ALTER TABLE "outbox_entries" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()::text;' >/dev/null
DEFAULT_INSTALLED=1

bash "$BASE_SCRIPT"
