'use client';

import type { ReactNode } from 'react';
import '@/app/v9.css';
import '@/app/v9-accessibility.css';
import '@/styles/theme.css';
import '@/styles/enterprise-ui.css';
import '@/styles/design-fixes.css';
import '@/styles/mobile-polish.css';
import '@/styles/platform-v7-dark-role-fixes.css';
import '@/styles/platform-v7-shell-clarity.css';
import '@/styles/platform-v7-work-surfaces.css';
import '@/styles/platform-v7-mobile-excellence.css';
import '@/styles/platform-v7-premium-visual-polish.css';
import '@/styles/platform-v7-final-polish.css';
import '@/styles/platform-v7-living-deal.css';
import '@/styles/platform-v7-premium-cockpit.css';
import '@/styles/platform-v7-entry-fix.css';
import '@/styles/platform-v7-mobile-hardening.css';
import '@/styles/platform-v7-mobile-reflow-p0.css';
import '@/styles/platform-v7-shell-restore.css';
import '@/styles/platform-v7-register-header-override.css';
import '@/styles/platform-v7-mobile-screenshot-fixes.css';
import '@/styles/platform-v7-mobile-shell-p1.css';
import '@/styles/platform-v7-shell-critical.css';
import '@/styles/platform-v7-public-header.css';
import '@/styles/platform-v7-public-auth.css';
import '@/styles/platform-v7-public-landing.css';
import '@/styles/platform-v7-public-mobile-safe-area.css';
import '@/styles/platform-v7-seller-mobile-usability.css';
import '@/styles/platform-v7-mobile-bottom-tools.css';
import '@/styles/platform-v7-seller-workspace-v2.css';
import '@/styles/platform-v7-public-entry-stable.css';
import '@/styles/platform-v7-role-cards-stable.css';
import '@/styles/platform-v7-protected-grid-stable.css';
import '@/styles/platform-v7-control-tower-mobile.css';
import '@/styles/platform-v7-bank-mobile.css';
import '@/styles/platform-v7-elevator-mobile.css';
import '@/styles/platform-v7-lab-mobile.css';
import '@/styles/platform-v7-compliance-mobile.css';
import '@/styles/platform-v7-arbitrator-mobile.css';
import '@/styles/platform-v7-executive-mobile.css';
import '@/styles/platform-v7-clean-deal-mobile.css';
import '@/styles/platform-v7-offer-to-deal-mobile.css';
import '@/styles/platform-v7-stable-shell.css';
import '@/styles/platform-v7-viewport-stability.css';
import '@/styles/platform-v7-adaptive-devices.css';
import '@/styles/platform-v7-i18n-cjk.css';
import '@/styles/platform-v7-public-webkit-safe.css';
import '@/styles/platform-v7-support-chat-polish.css';
import '@/styles/platform-v7-final-viewport-cleanup.css';
import '@/styles/platform-v7-public-hero-watermark.css';
import '@/styles/platform-v7-contextual-wheat-backgrounds.css';

export function PlatformV7FullStyleRuntime({ children }: { children: ReactNode }) {
  return children;
}
