import type { ExperienceCopy } from './PublicAiInActionExperience.types';

export const ZH_COPY: ExperienceCopy = {
    hero: {
      kicker: 'AI 实际运行', title: '从交易事实到可解释的下一步',
      lead: '本交互页面展示“透明价格”的角色范围 AI 如何检查可访问上下文、识别偏差、关联依据并为参与方准备决策。重要操作仍由人工控制。',
      primary: '启动交互演示', secondary: '返回首页',
      badges: ['角色范围访问', '服务器确认事实', '只读模式'],
      coreLabel: 'AI', coreMode: '角色范围', outputLabel: '当前输出',
      outputTitle: '风险已解释，下一步已准备', outputText: '原因、影响和依据集中在一张决策卡中。',
    },
    simulator: {
      eyebrow: '交互场景', title: '查看完整分析周期',
      lead: '选择角色和风险类型，启动演示、手动切换阶段、检查依据，并只确认已经准备好的操作。',
      scenarioLegend: '风险场景', roleLegend: '参与方角色',
      idle: '演示已暂停。点击“启动”或选择阶段。', running: 'AI 正在逐步处理可访问的交易上下文。',
      phaseLabel: '分析阶段', factsEyebrow: '可访问事实', factsLead: 'AI 仅查看所选角色可访问的事实。点击事实可查看依据。',
      evidenceLabel: '依据', aiEyebrow: '角色范围 AI', provider: 'server_role_scoped / read_only',
      decisionEyebrow: '决策卡', roleFocus: '角色重点', reason: '原因', impact: '影响', deadline: '控制期限', nextAction: '已准备的下一步',
      confirm: '确认已准备的操作', confirmed: '用户已确认操作', controlNote: '演示不会发送请求，也不会改变交易状态。',
      feedbackPrompt: 'AI 输出是否清晰？', useful: '清晰', detail: '需要细节',
      play: '启动', pause: '暂停', previous: '上一步', next: '下一步', restart: '重新开始',
      reducedMotion: '已启用减少动态效果：自动动画关闭，所有阶段均可手动查看。',
      contractScope: 'scope', contractData: 'data', contractMode: 'mode',
      waitingSummary: '正在收集上下文', waitingValue: '将在相应阶段显示',
    },
    roles: {
      buyer: { label: '买方', focus: '质量、文件、交付期限和结算依据' },
      seller: { label: '卖方', focus: '批次履约、义务、完整性和收款' },
      bank: { label: '银行', focus: '确认依据、资金风险和操作资格' },
    },
    scenarios: {
      quality: {
        label: '质量', title: '实验室报告尚未确认',
        summary: '结算保持阻断：批次质量尚未由实验室报告确认。',
        reason: '收货和实际重量已确认，但缺少关联实验室报告。交易条件要求在形成结算依据前确认质量。',
        impact: '资金无法释放，下一批发运可能错过约定窗口。', deadline: '距离控制期限 6 小时',
        action: '向实验室请求报告，并核对其与收货单的关联。', actionNote: 'AI 准备建议和依据，参与方确认发送。',
        riskBadge: '质量风险', attentionFact: 'quality',
        facts: {
          terms: { label: '条件', value: '结算前必须确认质量', detail: '交易条件规定，只有确认质量指标后才能形成结算依据。' },
          trip: { label: '运输', value: '按窗口到达', detail: '车辆与批次关联，并在约定窗口内到达粮库。' },
          acceptance: { label: '收货', value: '498.6 吨已确认', detail: '粮库确认实际重量并生成收货单。' },
          quality: { label: '质量', value: '缺少报告', detail: '可访问范围内没有与本次收货关联的已确认实验室报告。' },
          documents: { label: '文件', value: '收货单存在，材料不完整', detail: '收货单存在，但缺少实验室报告，依据材料不完整。' },
          settlement: { label: '结算', value: '已阻断', detail: '在质量和依据完整性确认前，资金操作不可用。' },
        },
      },
      documents: {
        label: '文件', title: '文件完整性检查未通过',
        summary: '下一阶段停止：文件存在，但所需版本和签名尚未确认。',
        reason: '履约事件已记录，但依据材料包含未签名的收货单。所选角色没有可用的确认版本。',
        impact: '履约时间延长，在有效依据出现前结算保持不可用。', deadline: '当前工作日结束前',
        action: '请求已签名收货单，并核对作者、时间以及与运输的关联。', actionNote: 'AI 指出具体材料缺口并准备修正请求。',
        riskBadge: '文件风险', attentionFact: 'documents',
        facts: {
          terms: { label: '条件', value: '需要已签名收货单', detail: '交易流程要求已签名收货单作为结算依据的一部分。' },
          trip: { label: '运输', value: '已完成', detail: '路线和到达由运输事件确认。' },
          acceptance: { label: '收货', value: '事件已确认', detail: '交付事实和重量记录在交易时间线中。' },
          quality: { label: '质量', value: '报告已确认', detail: '实验室报告与收货关联，并对所选角色可见。' },
          documents: { label: '文件', value: '版本未签名', detail: '最新可访问的收货单版本缺少所需签名确认。' },
          settlement: { label: '结算', value: '等待依据', detail: '金融层尚未获得足以允许操作的依据材料。' },
        },
      },
      settlement: {
        label: '结算', title: '操作金额与依据不一致',
        summary: '资金操作需要复核：操作金额与当前结算依据不同。',
        reason: '履约和文件均已确认，但准备的操作与当前资金依据版本不一致。AI 不确认银行事件，也不修改金额。',
        impact: '在依据版本和操作参数完成核对前，资金保持冻结。', deadline: '距离银行截止时间 3 小时',
        action: '核对依据版本、金额和用途，然后将依据包交给负责的银行员工。', actionNote: 'AI 准备核对和清单，授权参与方决定是否执行。',
        riskBadge: '资金风险', attentionFact: 'settlement',
        facts: {
          terms: { label: '条件', value: '价格和数量已固定', detail: '当前条件包含约定价格、数量和结算规则。' },
          trip: { label: '运输', value: '履约已完成', detail: '运输及控制点由确认事件关闭。' },
          acceptance: { label: '收货', value: '事实已确认', detail: '确认的收货单包含重量、日期和责任方。' },
          quality: { label: '质量', value: '已确认', detail: '实验室报告可用并与批次关联。' },
          documents: { label: '文件', value: '材料已确认', detail: '所需文件版本存在并与履约事件关联。' },
          settlement: { label: '结算', value: '金额不一致', detail: '准备的操作金额与当前依据版本中的金额不同。' },
        },
      },
    },
    phases: [
      { title: '访问检查', short: '角色与范围', narrative: '服务器确定角色，并仅选择允许访问的交易事实。', output: '上下文限制在所选角色范围内。' },
      { title: '信号识别', short: '偏差', narrative: 'AI 对比阶段、期限、文件和付款依据。', output: '已突出显示影响下一阶段的偏差。' },
      { title: '解释构建', short: '原因与依据', narrative: '信号与事件、文件、责任方和控制期限关联。', output: '原因由可访问依据支持。' },
      { title: '影响评估', short: '时间与资金', narrative: 'AI 显示被阻断内容以及运营或资金风险。', output: '影响不包含保证或猜测。' },
      { title: '下一步', short: '建议', narrative: 'AI 准备具体操作，并将决策交给授权参与方。', output: '重要操作需要人工确认。' },
    ],
    principles: {
      eyebrow: 'AI 当前能力', title: '工作区内的五项实际功能',
      lead: '本页展示已实现的只读体验：AI 使用服务器确认的角色上下文、解释输出，并且不替代参与方权限。',
      cards: [
        { icon: 'participants', title: '遵守角色范围', body: '仅使用服务器允许当前角色和组织访问的交易与事实。' },
        { icon: 'risk', title: '识别偏差', body: '对比状态、期限、文件、质量、路线和结算依据。' },
        { icon: 'documents', title: '解释依据', body: '通过具体事件、文件、来源和责任方说明原因。' },
        { icon: 'intelligence', title: '准备操作', body: '形成下一步、检查清单或请求，但不会自主执行重要命令。' },
      ],
    },
    boundary: {
      eyebrow: '控制与信任', title: '清晰边界，而不是魔法',
      lead: '用户可以看到输出基于哪些数据、AI 不能做什么，以及何处需要确认。',
      cards: [
        { icon: 'compliance', label: '访问', title: '仅限允许范围', body: '其他角色、组织和交易不会进入回答上下文。' },
        { icon: 'documents', label: '依据', title: '事实可检查', body: '每个输出都关联到可访问事件、文件或服务器状态。' },
        { icon: 'risk', label: '不确定性', title: '不保证结果', body: 'AI 展示风险和建议，但不保证业务结果。' },
        { icon: 'check', label: '权限', title: '最终操作由人工执行', body: '发送、修改交易和资金操作都需要授权参与方。' },
      ],
    },
    final: {
      eyebrow: '继续使用', title: '打开工作区，在角色范围内使用 AI',
      lead: '工作区中的助手使用您的角色可访问的服务器数据。本公开页面仅是匿名交互说明。',
      primary: '登录平台', secondary: '查看演示交易',
    },
  };
