import type { ExperienceCopy } from './PublicAiInActionExperience.types';

export const EN_COPY: ExperienceCopy = {
    hero: {
      kicker: 'AI in action',
      title: 'From deal facts to an explainable next step',
      lead: 'This interactive walkthrough shows how Transparent Price role-scoped AI checks accessible context, detects a deviation, links it to evidence and prepares a decision for the participant. The consequential action remains under human control.',
      primary: 'Start the interactive walkthrough',
      secondary: 'Back to home',
      badges: ['Role-scoped access', 'Server-confirmed facts', 'Read-only mode'],
      coreLabel: 'AI',
      coreMode: 'role-scoped layer',
      outputLabel: 'Current output',
      outputTitle: 'Risk explained — next step ready',
      outputText: 'Cause, impact and evidence are assembled in one decision card.',
    },
    simulator: {
      eyebrow: 'Interactive scenario',
      title: 'Follow the complete reasoning cycle',
      lead: 'Choose a role and a risk scenario. Run the walkthrough, move through the stages manually, inspect evidence and confirm only the prepared action.',
      scenarioLegend: 'Risk scenario',
      roleLegend: 'Participant role',
      idle: 'The walkthrough is paused. Select Start or choose a stage.',
      running: 'AI is processing the accessible deal context stage by stage.',
      phaseLabel: 'Analysis stage',
      factsEyebrow: 'Accessible facts',
      factsLead: 'AI sees only facts available to the selected role. Select a fact to inspect its evidence.',
      evidenceLabel: 'Evidence',
      aiEyebrow: 'Role-scoped AI',
      provider: 'server_role_scoped / read_only',
      decisionEyebrow: 'Decision card',
      roleFocus: 'Role focus',
      reason: 'Reason',
      impact: 'Impact',
      deadline: 'Control deadline',
      nextAction: 'Prepared next step',
      confirm: 'Confirm the prepared action',
      confirmed: 'Action confirmed by the user',
      controlNote: 'The demonstration sends no requests and does not change deal state.',
      feedbackPrompt: 'How clear is the AI output?',
      useful: 'Clear',
      detail: 'Need detail',
      play: 'Start',
      pause: 'Pause',
      previous: 'Back',
      next: 'Next',
      restart: 'Restart',
      reducedMotion: 'Reduced motion is enabled: autoplay is disabled and every stage remains available manually.',
      contractScope: 'scope',
      contractData: 'data',
      contractMode: 'mode',
      waitingSummary: 'Context is still being assembled',
      waitingValue: 'Available after the corresponding stage',
    },
    roles: {
      buyer: { label: 'Buyer', focus: 'Quality, documents, delivery timing and settlement grounds' },
      seller: { label: 'Seller', focus: 'Lot execution, obligations, completeness and payment receipt' },
      bank: { label: 'Bank', focus: 'Confirmed grounds, financial exposure and operation eligibility' },
    },
    scenarios: {
      quality: {
        label: 'Quality', title: 'Laboratory protocol is not confirmed',
        summary: 'Settlement remains blocked because lot quality is not confirmed by a laboratory protocol.',
        reason: 'Acceptance and actual weight are confirmed, but the linked laboratory protocol is missing. Deal terms require confirmed quality before settlement grounds can be formed.',
        impact: 'Funds cannot be released and the next shipment may miss its agreed window.',
        deadline: '6 hours to the control deadline',
        action: 'Request the protocol from the laboratory and verify its link to the acceptance act.',
        actionNote: 'AI prepares the recommendation and evidence; the participant confirms sending.',
        riskBadge: 'Quality risk', attentionFact: 'quality',
        facts: {
          terms: { label: 'Terms', value: 'Quality required before settlement', detail: 'The deal terms state that settlement grounds arise only after quality indicators are confirmed.' },
          trip: { label: 'Trip', value: 'Arrived within the window', detail: 'The trip is linked to the lot and arrived at the elevator within the agreed window.' },
          acceptance: { label: 'Acceptance', value: '498.6 t confirmed', detail: 'The elevator confirmed actual weight and created the acceptance act.' },
          quality: { label: 'Quality', value: 'Protocol missing', detail: 'No confirmed laboratory protocol linked to this acceptance is present in the accessible scope.' },
          documents: { label: 'Documents', value: 'Act present, set incomplete', detail: 'The acceptance act exists, but the evidence set is incomplete without the laboratory protocol.' },
          settlement: { label: 'Settlement', value: 'Blocked', detail: 'The money operation is unavailable until quality and evidence completeness are confirmed.' },
        },
      },
      documents: {
        label: 'Documents', title: 'Document completeness check failed',
        summary: 'The next stage is stopped because the document exists but the required version and signature are not confirmed.',
        reason: 'Execution is recorded, yet the evidence set contains an unsigned acceptance act. The selected role has no confirmed version available.',
        impact: 'Execution time increases and settlement remains unavailable until a valid ground appears.',
        deadline: 'Before the end of the operating day',
        action: 'Request the signed act and verify its author, time and relation to the trip.',
        actionNote: 'AI points to the exact evidence gap and prepares a remediation request.',
        riskBadge: 'Document risk', attentionFact: 'documents',
        facts: {
          terms: { label: 'Terms', value: 'Signed act required', detail: 'The deal procedure requires a signed acceptance act as part of settlement grounds.' },
          trip: { label: 'Trip', value: 'Completed', detail: 'Route and arrival are confirmed by trip events.' },
          acceptance: { label: 'Acceptance', value: 'Event confirmed', detail: 'Delivery fact and weight are recorded in the deal chronology.' },
          quality: { label: 'Quality', value: 'Protocol confirmed', detail: 'The laboratory protocol is linked to acceptance and available to the selected role.' },
          documents: { label: 'Documents', value: 'Unsigned version', detail: 'The latest accessible act version lacks the required signature confirmation.' },
          settlement: { label: 'Settlement', value: 'Awaiting grounds', detail: 'The financial layer does not receive a sufficient evidence set to allow the operation.' },
        },
      },
      settlement: {
        label: 'Settlement', title: 'Operation amount conflicts with the ground',
        summary: 'The money operation requires review because its amount differs from the current settlement ground.',
        reason: 'Execution and documents are confirmed, but the prepared operation does not match the current version of the financial ground. AI does not confirm the bank event or change the amount.',
        impact: 'Funds remain on hold until the ground version and operation parameters are reconciled.',
        deadline: '3 hours to bank cut-off',
        action: 'Reconcile the ground version, amount and payment purpose, then transfer the evidence pack to the responsible bank employee.',
        actionNote: 'AI prepares the reconciliation and checklist; an authorised participant decides on the operation.',
        riskBadge: 'Financial risk', attentionFact: 'settlement',
        facts: {
          terms: { label: 'Terms', value: 'Price and volume fixed', detail: 'The current terms contain agreed price, volume and settlement rules.' },
          trip: { label: 'Trip', value: 'Execution completed', detail: 'The trip and its checkpoints are closed by confirmed events.' },
          acceptance: { label: 'Acceptance', value: 'Fact confirmed', detail: 'Weight, date and responsible participant are present in the confirmed act.' },
          quality: { label: 'Quality', value: 'Confirmed', detail: 'The laboratory protocol is available and linked to the lot.' },
          documents: { label: 'Documents', value: 'Set confirmed', detail: 'Required document versions are present and linked to execution events.' },
          settlement: { label: 'Settlement', value: 'Amount mismatch', detail: 'The prepared operation amount differs from the current ground version.' },
        },
      },
    },
    phases: [
      { title: 'Access check', short: 'Role and scope', narrative: 'The server resolves the role and selects only permitted deal facts.', output: 'Context is limited to the selected role.' },
      { title: 'Signal detection', short: 'Deviation', narrative: 'AI compares stages, deadlines, documents and payment grounds.', output: 'A deviation affecting the next stage is highlighted.' },
      { title: 'Explanation', short: 'Cause and evidence', narrative: 'The signal is linked to an event, document, owner and control deadline.', output: 'The cause is supported by accessible evidence.' },
      { title: 'Impact assessment', short: 'Time and money', narrative: 'AI shows what is blocked and where operational or financial exposure appears.', output: 'Impact is stated without guarantees or guesswork.' },
      { title: 'Next step', short: 'Recommendation', narrative: 'AI prepares a concrete action and hands the decision to the authorised participant.', output: 'A consequential action requires human confirmation.' },
    ],
    principles: {
      eyebrow: 'What AI does now', title: 'Five practical functions inside the workspace',
      lead: 'This page demonstrates the implemented read-only experience: AI uses server-confirmed role context, explains its output and does not replace participant authority.',
      cards: [
        { icon: 'participants', title: 'Respects the role', body: 'Uses only deals and facts that the server permits for the current role and organisation.' },
        { icon: 'risk', title: 'Finds deviation', body: 'Compares status, deadline, document, quality, route and settlement grounds.' },
        { icon: 'documents', title: 'Explains evidence', body: 'Shows the cause through concrete events, documents, sources and owners.' },
        { icon: 'intelligence', title: 'Prepares action', body: 'Builds the next step, checklist or request without executing a consequential command.' },
      ],
    },
    boundary: {
      eyebrow: 'Control and trust', title: 'Clear boundaries instead of magic',
      lead: 'The user can see which data supports the output, what AI cannot do and where confirmation is required.',
      cards: [
        { icon: 'compliance', label: 'Access', title: 'Permitted scope only', body: 'Other roles, organisations and deals never enter the answer context.' },
        { icon: 'documents', label: 'Evidence', title: 'Facts are inspectable', body: 'Every output connects to an accessible event, document or server state.' },
        { icon: 'risk', label: 'Uncertainty', title: 'No guaranteed outcomes', body: 'AI presents risk and a recommendation without guaranteeing the business result.' },
        { icon: 'check', label: 'Authority', title: 'People take the final action', body: 'Sending, deal mutation and money operations require an authorised participant.' },
      ],
    },
    final: {
      eyebrow: 'Continue working', title: 'Open your workspace and use AI inside your role scope',
      lead: 'Inside the workspace the assistant uses server data accessible to your role. This public page remains an anonymised interactive explanation.',
      primary: 'Sign in to the platform', secondary: 'Review the demonstration deal',
    },
  };
