import { readdirSync, readFileSync, statSync } from 'fs';
import { join, basename } from 'path';

/**
 * Anti-regression guard (Professional Codebase Audit, C2).
 *
 * Fails if backend source under apps/api/src reintroduces forbidden
 * fake-maturity / fake-live marketing copy, or AI/generation traces. The
 * platform is controlled-pilot / pre-integration; these claims must not appear
 * in shipping code until proven by real integrations and load tests.
 *
 * This guard scans CODE only (apps/api/src). It deliberately excludes itself
 * (it necessarily contains the banned phrases) and the audit docs under
 * docs/platform-v7/audit/** which legitimately quote them.
 */

// Precise multi-word phrases — chosen to avoid false positives on legitimate
// tokens like "production" (e.g. deploy-production) or "live" alone.
const FORBIDDEN_COPY = [
  'production-ready',
  'fully live',
  'fully integrated',
  'bank connected',
  'fgis connected',
  'edo connected',
  'live payment active',
  'platform guarantees payment',
  'platform releases money itself',
  'supports 100k',
  'supports hundreds of thousands',
  'load-tested',
  'load tested',
  'bank-grade',
  'no risks',
  'all integrations ready',
];

const AI_TRACES = [
  'generated by ai',
  'ai-generated',
  'vibe-coded',
  'as an ai assistant',
  'as an ai language model',
];

const SELF = basename(__filename); // forbidden-copy.guard.spec.* — skip self
const ROOT = join(__dirname, '..', '..'); // apps/api/src

function collectSourceFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist') continue;
      collectSourceFiles(full, acc);
    } else if (/\.(ts|tsx)$/.test(entry) && basename(full) !== SELF) {
      acc.push(full);
    }
  }
  return acc;
}

function findViolations(phrases: string[]): string[] {
  const violations: string[] = [];
  for (const file of collectSourceFiles(ROOT)) {
    const lower = readFileSync(file, 'utf8').toLowerCase();
    for (const phrase of phrases) {
      if (lower.includes(phrase)) {
        violations.push(`${file.replace(ROOT, 'apps/api/src')}: "${phrase}"`);
      }
    }
  }
  return violations;
}

describe('forbidden copy guard (Professional Codebase Audit C2)', () => {
  it('apps/api/src contains no fake-maturity / fake-live marketing copy', () => {
    expect(findViolations(FORBIDDEN_COPY)).toEqual([]);
  });

  it('apps/api/src contains no AI/generation traces', () => {
    expect(findViolations(AI_TRACES)).toEqual([]);
  });
});
