export const federalCompanyProfiles = [
  {
    id: 'fed-buyer-ozk',
    name: 'АО «Объединенная зерновая компания»',
    segment: 'Федеральный buyer / инфраструктурный контур',
    regions: ['Москва', 'ЦФО', 'ЮФО', 'экспортный контур'],
    focus: ['пшеница', 'интервенции', 'экспорт'],
    value: 'Инфраструктурный buyer с сильным экспортным и интервенционным контуром.',
    verification: 'каталог federal / ручной KYB перед live',
    paymentDiscipline: 'reserve / hold / manual bank rail',
    logisticsReadiness: 'экспортный и терминальный контур, нужен route + docs control',
    financeReadiness: 'high для bank-ready сделок',
    activeModules: [{ label: 'Компании', href: '/companies' }, { label: 'Финансы', href: '/finance' }, { label: 'Аукционы', href: '/auctions' }],
    strengths: ['инфраструктурный вес', 'экспортный контур', 'масштаб'],
    risks: ['ручной KYB перед боевым подключением', 'нужен отдельный лимит и compliance-flow'],
    lastSignal: 'Федеральный каталог · buyer / export / interventions'
  },
  {
    id: 'fed-buyer-demetra',
    name: 'ООО «Деметра Трейдинг»',
    segment: 'Федеральный buyer / трейдер',
    regions: ['Краснодарский край', 'ЦФО', 'ЮФО', 'Поволжье'],
    focus: ['пшеница', 'ячмень', 'кукуруза', 'масличные'],
    value: 'Сильный trader с ценовым контуром, авансированием и сетью элеваторов.',
    verification: 'каталог federal / ручной KYB перед live',
    paymentDiscipline: 'reserve / advance / staged release',
    logisticsReadiness: 'сильный зерновой логистический контур',
    financeReadiness: 'high',
    activeModules: [{ label: 'Компании', href: '/companies' }, { label: 'Лоты', href: '/lots' }, { label: 'Финансы', href: '/finance' }],
    strengths: ['цены и авансирование', 'сеть элеваторов', 'экспортный контур'],
    risks: ['нужен отдельный договорной шаблон', 'следить за basis и документами'],
    lastSignal: 'Федеральный каталог · buyer / advance / elevators'
  },
  {
    id: 'fed-buyer-aston',
    name: 'АО «Астон»',
    segment: 'Федеральный buyer / экспортёр',
    regions: ['Ростовская область', 'ЮФО', 'экспортный контур'],
    focus: ['зерно', 'масличные', 'экспорт'],
    value: 'Крупный экспортный и перерабатывающий контур.',
    verification: 'каталог federal / ручной KYB перед live',
    paymentDiscipline: 'reserve / callback / export docs',
    logisticsReadiness: 'сильный портовый и экспортный контур',
    financeReadiness: 'high',
    activeModules: [{ label: 'Компании', href: '/companies' }, { label: 'Документы', href: '/documents' }, { label: 'Финансы', href: '/finance' }],
    strengths: ['экспорт', 'масштаб', 'плотный procurement контур'],
    risks: ['нужен отдельный экспортный пакет', 'повышенные требования к документам'],
    lastSignal: 'Федеральный каталог · export buyer'
  },
  {
    id: 'fed-buyer-rusagro',
    name: 'ПАО «Группа «Русагро»',
    segment: 'Федеральный buyer / переработчик',
    regions: ['ЦФО', 'Белгородская область', 'Тамбовская область', 'ДФО'],
    focus: ['подсолнечник', 'соя', 'зерно'],
    value: 'Крупный агрохолдинг и переработчик с широкой географией.',
    verification: 'каталог federal / ручной KYB перед live',
    paymentDiscipline: 'лимит + reserve + callback',
    logisticsReadiness: 'готов к крупным потокам, нужен agreed slotting',
    financeReadiness: 'high',
    activeModules: [{ label: 'Компании', href: '/companies' }, { label: 'Финансы', href: '/finance' }, { label: 'Лоты', href: '/lots' }],
    strengths: ['масштаб', 'переработка', 'широкая география'],
    risks: ['сложный договорной и quality контур', 'нужен bank-ready пакет'],
    lastSignal: 'Федеральный каталог · processor / buyer'
  },
  {
    id: 'fed-buyer-miratorg',
    name: 'АПХ «Мираторг»',
    segment: 'Федеральный buyer / кормовой контур',
    regions: ['Белгородская область', 'Брянская область', 'ЦФО'],
    focus: ['кукуруза', 'пшеница', 'ячмень'],
    value: 'Сильный кормовой и производственный контур с собственной агроинфраструктурой.',
    verification: 'каталог federal / ручной KYB перед live',
    paymentDiscipline: 'reserve / staged release / limit control',
    logisticsReadiness: 'высокая, но нужен строгий slot discipline',
    financeReadiness: 'medium-high',
    activeModules: [{ label: 'Компании', href: '/companies' }, { label: 'Dispatch', href: '/dispatch' }, { label: 'Финансы', href: '/finance' }],
    strengths: ['сильный кормовой контур', 'вертикальная интеграция', 'предсказуемые объёмы'],
    risks: ['жёсткий quality control', 'нужен устойчивый dispatch rail'],
    lastSignal: 'Федеральный каталог · feed buyer'
  },
  {
    id: 'fed-buyer-chernkizovo',
    name: 'Группа «Черкизово»',
    segment: 'Федеральный buyer / кормовой и перерабатывающий контур',
    regions: ['Липецкая область', 'Тамбовская область', 'ЦФО'],
    focus: ['пшеница', 'кукуруза', 'ячмень'],
    value: 'Крупный buyer для кормового и перерабатывающего сценария.',
    verification: 'каталог federal / ручной KYB перед live',
    paymentDiscipline: 'лимит / reserve / callback',
    logisticsReadiness: 'сильная внутренняя логистика, нужен agreed intake rail',
    financeReadiness: 'high',
    activeModules: [{ label: 'Компании', href: '/companies' }, { label: 'Приёмка', href: '/receiving' }, { label: 'Финансы', href: '/finance' }],
    strengths: ['регулярный спрос', 'понятный intake', 'масштаб'],
    risks: ['строгий compliance к партиям', 'требуется стабильная quality traceability'],
    lastSignal: 'Федеральный каталог · feed / processor'
  },
  {
    id: 'fed-buyer-cargill-ru',
    name: 'ООО «Каргилл»',
    segment: 'Международный / федеральный buyer',
    regions: ['ЦФО', 'ЮФО', 'экспортный контур'],
    focus: ['зерно', 'масличные', 'экспорт'],
    value: 'Контур для международного качества исполнения и экспортного документооборота.',
    verification: 'каталог federal / расширенный KYB и export-compliance',
    paymentDiscipline: 'reserve / export docs / callback',
    logisticsReadiness: 'высокая, но критичен документный и quality rail',
    financeReadiness: 'high',
    activeModules: [{ label: 'Компании', href: '/companies' }, { label: 'Документы', href: '/documents' }, { label: 'Аукционы', href: '/auctions' }],
    strengths: ['международный контур', 'качество', 'экспортная экспертиза'],
    risks: ['повышенные требования к контракту и доказательствам', 'ручной compliance before live'],
    lastSignal: 'Федеральный каталог · international / export'
  },
  {
    id: 'fed-buyer-bunge-ru',
    name: 'ООО «Бунге СНГ»',
    segment: 'Федеральный buyer / масличный контур',
    regions: ['Воронежская область', 'ЦФО', 'ЮФО'],
    focus: ['подсолнечник', 'соя', 'масличные'],
    value: 'Сильный buyer для масличных и переработки.',
    verification: 'каталог federal / ручной KYB перед live',
    paymentDiscipline: 'reserve / quality-linked release',
    logisticsReadiness: 'хорошая, важен контроль очереди и inbound lab',
    financeReadiness: 'medium-high',
    activeModules: [{ label: 'Компании', href: '/companies' }, { label: 'Лаборатория', href: '/lab' }, { label: 'Финансы', href: '/finance' }],
    strengths: ['масличный контур', 'качество', 'переработка'],
    risks: ['quality dispute sensitivity', 'нужна устойчивая цепочка проб'],
    lastSignal: 'Федеральный каталог · oilseeds / processor'
  }
];
