'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { LogIn, LogOut } from 'lucide-react';
import { BrandMark } from '@/components/v7r/BrandMark';

type Lang = 'ru' | 'en' | 'zh';
const KEY = 'pc-v7-language';
const roles = {
  ru: ['Продавец', 'Покупатель', 'Логистика', 'Элеватор', 'Лаборатория', 'Сюрвейер', 'Банк', 'Арбитр', 'Оператор'],
  en: ['Seller', 'Buyer', 'Logistics', 'Elevator', 'Laboratory', 'Surveyor', 'Bank', 'Arbitrator', 'Operator'],
  zh: ['卖方', '买方', '物流', '粮仓', '实验室', '检验员', '银行', '仲裁员', '运营方'],
} as const;
const copy = {
  ru: { brand:'Прозрачная Цена', login:'Войти', exit:'Выход', title:'Подключение компании к контуру сделки', lead:'Заявка фиксирует роль, организацию и ответственного. Доступ в рабочий кабинет открывается только после проверки.', role:'Роль участника', org:'Организация', req:'Реквизиты', person:'Ответственный', status:'Статусы проверки', send:'Отправить заявку на проверку', already:'Уже есть доступ — войти', fields:['Тип участника','Название организации','Регион','ИНН','КПП','ОГРН / ОГРНИП','ФИО','Должность','Телефон','Email'], states:['Заявка создана','Ожидает проверки','Требуется уточнение','Допущен','Отклонён'] },
  en: { brand:'Transparent Price', login:'Sign in', exit:'Exit', title:'Connect a company to the deal circuit', lead:'The application fixes the role, organisation and responsible person. Workspace access opens only after review.', role:'Participant role', org:'Organisation', req:'Requisites', person:'Responsible person', status:'Review statuses', send:'Submit application for review', already:'Already have access — sign in', fields:['Participant type','Organisation name','Region','TIN','KPP','OGRN / OGRNIP','Full name','Position','Phone','Email'], states:['Application created','Awaiting review','Clarification required','Approved','Declined'] },
  zh: { brand:'透明价格', login:'登录', exit:'退出', title:'将公司接入交易闭环', lead:'申请固定角色、组织和负责人。工作区访问仅在审核后开放。', role:'参与方角色', org:'组织', req:'账户信息', person:'负责人', status:'审核状态', send:'提交审核申请', already:'已有访问权限 — 登录', fields:['参与方类型','组织名称','地区','税号','KPP','OGRN / OGRNIP','全名','职位','电话','Email'], states:['申请已创建','等待审核','需要补充说明','已准入','已拒绝'] },
} as const;
const values = ['seller','buyer','logistics','elevator','lab','surveyor','bank','arbitrator','operator'];
function readLang(): Lang { const v = window.localStorage.getItem(KEY); return v === 'en' || v === 'zh' ? v : 'ru'; }
export function RegisterCleanClient({ selectedRole }: { selectedRole: string }) {
  const [lang, setLang] = useState<Lang>('ru');
  useEffect(() => { const run = () => setLang(readLang()); run(); const id = window.setInterval(run, 400); window.addEventListener('storage', run); return () => { window.clearInterval(id); window.removeEventListener('storage', run); }; }, []);
  const t = copy[lang];
  return <main className='p7-register-clean' data-lang={lang} data-p7-no-translate='true'><style>{css}</style><header><Link href='/platform-v7' className='brand'><BrandMark size={42}/><b>{t.brand}</b></Link><nav><Link href='/platform-v7/login'><LogIn size={16}/>{t.login}</Link><Link href='/platform-v7'><LogOut size={16}/>{t.exit}</Link></nav></header><section className='hero'><h1>{t.title}</h1><p>{t.lead}</p></section><section className='card'><strong>{t.role}</strong><select defaultValue={selectedRole}>{roles[lang].map((role,i)=><option key={role} value={values[i]}>{role}</option>)}</select></section><Block title={t.org} items={t.fields.slice(0,3)}/><Block title={t.req} items={t.fields.slice(3,6)}/><Block title={t.person} items={t.fields.slice(6)}/><section className='card'><strong>{t.status}</strong><div className='states'>{t.states.map(s=><span key={s}>{s}</span>)}</div></section><div className='cta'><Link href='/platform-v7/onboarding'>{t.send}</Link><Link href='/platform-v7/login'>{t.already}</Link></div></main>;
}
function Block({title,items}:{title:string;items:readonly string[]}){return <section className='card'><strong>{title}</strong><div className='grid'>{items.map(x=><label key={x}><span>{x}</span><input /></label>)}</div></section>}
const css = `.p7-register-clean{display:grid;gap:14px;max-width:980px;margin:0 auto;padding:14px 16px 30px;color:#111827;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.p7-register-clean *{box-sizing:border-box}.p7-register-clean a{text-decoration:none;color:inherit}.p7-register-clean header{position:sticky;top:max(8px,env(safe-area-inset-top));z-index:30;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:12px;padding:13px 14px;border:1px solid rgba(15,23,42,.08);border-radius:26px;background:rgba(255,255,255,.94);box-shadow:0 16px 38px rgba(15,23,42,.055)}.brand{display:flex;align-items:center;gap:10px}.brand b{font-size:20px;font-weight:950}.p7-register-clean nav{display:flex;gap:8px}.p7-register-clean nav a{min-height:40px;display:inline-flex;align-items:center;gap:7px;padding:0 13px;border-radius:15px;background:#fff;border:1px solid rgba(15,23,42,.1);font-weight:900}.hero{padding:30px;border-radius:30px;background:linear-gradient(135deg,#0b7a3f,#075f32);color:#fff}.hero h1{margin:0;font-size:clamp(34px,6vw,64px);line-height:1;letter-spacing:-.05em}.hero p{max-width:740px;font-size:16px;line-height:1.5}.card{background:rgba(255,255,255,.92);border:1px solid rgba(15,23,42,.08);border-radius:26px;padding:18px;display:grid;gap:13px;box-shadow:0 16px 38px rgba(15,23,42,.055)}.card>strong{font-size:13px;font-weight:950;text-transform:uppercase;color:#66758a}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card label{display:grid;gap:6px}.card label span{font-size:12.5px;font-weight:850;color:#66758a}.card input,.card select,select{min-height:46px;border-radius:15px;border:1px solid rgba(15,23,42,.1);background:#fff;padding:0 14px;font-size:15px;color:#111827}.states{display:flex;gap:8px;flex-wrap:wrap}.states span{padding:8px 10px;border-radius:999px;background:rgba(0,122,47,.08);color:#087a3b;font-size:12px;font-weight:900}.cta{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cta a{min-height:52px;border-radius:18px;display:flex;align-items:center;justify-content:center;text-align:center;font-weight:950}.cta a:first-child{background:#087a3b;color:#fff}.cta a:last-child{background:rgba(0,122,47,.08);color:#087a3b}.p7-register-clean[data-lang='zh']{font-family:-apple-system,BlinkMacSystemFont,'PingFang SC','Noto Sans SC','Microsoft YaHei','Segoe UI',sans-serif}.p7-register-clean[data-lang='zh'] *{letter-spacing:0!important;word-break:keep-all;overflow-wrap:anywhere}.p7-register-clean[data-lang='zh'] h1{line-height:1.12}@media(max-width:680px){.grid,.cta{grid-template-columns:1fr}.p7-register-clean nav a:first-child{display:none}.hero{padding:24px;border-radius:26px}.hero h1{font-size:34px}}`;
