'use client';

import Link from 'next/link';
import { useLocale, useTranslations } from 'next-intl';
import { LogIn, LogOut } from 'lucide-react';
import { PublicSiteHeader } from '@/components/platform-v7/PublicSiteHeader';

// Копия — в apps/web/messages/*.json (namespace `register`).
const roleValues = ['seller', 'buyer', 'logistics', 'elevator', 'lab', 'surveyor', 'bank', 'arbitrator', 'operator'] as const;
const fieldKeys = ['type', 'orgName', 'region', 'inn', 'kpp', 'ogrn', 'fullName', 'position', 'phone', 'email'] as const;
const stateKeys = ['created', 'awaiting', 'clarify', 'approved', 'declined'] as const;

export function RegisterCleanClient({ selectedRole }: { selectedRole: string }) {
  const t = useTranslations('register');
  const lang = useLocale();
  const fields = fieldKeys.map((key) => t(`fields.${key}`));
  return <main className='p7-register-clean' data-lang={lang} data-p7-no-translate='true'><style>{css}</style><PublicSiteHeader ariaLabel={t('brand')} actions={<><Link href='/platform-v7/login' className='pc-site-action'><LogIn size={16}/>{t('login')}</Link><Link href='/platform-v7' className='pc-site-action'><LogOut size={16}/>{t('exit')}</Link></>}/><section className='hero'><h1>{t('title')}</h1><p>{t('lead')}</p></section><section className='card'><strong>{t('role')}</strong><select defaultValue={selectedRole}>{roleValues.map((value)=><option key={value} value={value}>{t(`roles.${value}`)}</option>)}</select></section><Block title={t('org')} items={fields.slice(0,3)}/><Block title={t('req')} items={fields.slice(3,6)}/><Block title={t('person')} items={fields.slice(6)}/><section className='card'><strong>{t('status')}</strong><div className='states'>{stateKeys.map(key=><span key={key}>{t(`states.${key}`)}</span>)}</div></section><div className='cta'><Link href='/platform-v7/onboarding'>{t('send')}</Link><Link href='/platform-v7/login'>{t('already')}</Link></div></main>;
}
function Block({title,items}:{title:string;items:readonly string[]}){return <section className='card'><strong>{title}</strong><div className='grid'>{items.map(x=><label key={x}><span>{x}</span><input /></label>)}</div></section>}
const css = `.p7-register-clean{display:grid;gap:14px;max-width:980px;margin:0 auto;padding:80px 16px 30px;color:#111827;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.p7-register-clean *{box-sizing:border-box}.p7-register-clean a{text-decoration:none;color:inherit}.brand{display:flex;align-items:center;gap:10px}.brand b{font-size:20px;font-weight:950}.p7-register-clean nav{display:flex;gap:8px}.p7-register-clean nav a{min-height:40px;display:inline-flex;align-items:center;gap:7px;padding:0 13px;border-radius:15px;background:#fff;border:1px solid rgba(15,23,42,.1);font-weight:900}.hero{padding:30px;border-radius:30px;background:linear-gradient(135deg,#0b7a3f,#075f32);color:#fff}.hero h1{margin:0;font-size:clamp(34px,6vw,64px);line-height:1;letter-spacing:-.05em}.hero p{max-width:740px;font-size:16px;line-height:1.5}.card{background:rgba(255,255,255,.92);border:1px solid rgba(15,23,42,.08);border-radius:26px;padding:18px;display:grid;gap:13px;box-shadow:0 16px 38px rgba(15,23,42,.055)}.card>strong{font-size:13px;font-weight:950;text-transform:uppercase;color:#66758a}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card label{display:grid;gap:6px}.card label span{font-size:12.5px;font-weight:850;color:#66758a}.card input,.card select,select{min-height:46px;border-radius:15px;border:1px solid rgba(15,23,42,.1);background:#fff;padding:0 14px;font-size:15px;color:#111827}.states{display:flex;gap:8px;flex-wrap:wrap}.states span{padding:8px 10px;border-radius:999px;background:rgba(0,122,47,.08);color:#087a3b;font-size:12px;font-weight:900}.cta{display:grid;grid-template-columns:1fr 1fr;gap:10px}.cta a{min-height:52px;border-radius:18px;display:flex;align-items:center;justify-content:center;text-align:center;font-weight:950}.cta a:first-child{background:#087a3b;color:#fff}.cta a:last-child{background:rgba(0,122,47,.08);color:#087a3b}.p7-register-clean[data-lang='zh']{font-family:-apple-system,BlinkMacSystemFont,'PingFang SC','Noto Sans SC','Microsoft YaHei','Segoe UI',sans-serif}.p7-register-clean[data-lang='zh'] *{letter-spacing:0!important;word-break:keep-all;overflow-wrap:anywhere}.p7-register-clean[data-lang='zh'] h1{line-height:1.12}@media(max-width:680px){.grid,.cta{grid-template-columns:1fr}.p7-register-clean nav a:first-child{display:none}.hero{padding:24px;border-radius:26px}.hero h1{font-size:34px}}`;
