-- Historical compatibility migration.
--
-- This migration was originally generated for the retired SQLite datasource and
-- used SQLite-only DATETIME/REAL/TEXT storage for tables that are already created
-- by the preceding `0001_postgresql_initial` PostgreSQL baseline.
--
-- The directory and migration identifier are intentionally preserved so Prisma's
-- ordered migration history remains deterministic. On PostgreSQL this migration
-- is a documented no-op; deleting it or applying its legacy DDL would either break
-- migration history or attempt to recreate canonical tables with incompatible
-- column types.
--
-- Canonical PostgreSQL definitions for outbox_entries, disputes,
-- dispute_money_holds, dispute_evidence, evidence_files and audit_events live in
-- `0001_postgresql_initial/migration.sql` and subsequent PostgreSQL migrations.
SELECT 1;
