import { PLATFORM_V7_LEXICON } from './lexicon';
import {
  PLATFORM_V7_AI_ROUTE,
  PLATFORM_V7_ANTI_BYPASS_ROUTE,
  PLATFORM_V7_AUTH_ROUTE,
  PLATFORM_V7_BANK_CLEAN_ROUTE,
  PLATFORM_V7_BANK_ESCROW_ROUTE,
  PLATFORM_V7_BANK_EVENTS_ROUTE,
  PLATFORM_V7_BANK_FACTORING_ROUTE,
  PLATFORM_V7_BANK_PAYMENT_BASIS_ROUTE,
  PLATFORM_V7_BANK_ROUTE,
  PLATFORM_V7_BUYER_LOT_ROUTE,
  PLATFORM_V7_BUYER_RFQ_NEW_ROUTE,
  PLATFORM_V7_BUYER_RFQ_ROUTE,
  PLATFORM_V7_BUYER_ROUTE,
  PLATFORM_V7_CANONICAL_RECONCILIATION_ROUTE,
  PLATFORM_V7_CONNECTORS_ROUTE,
  PLATFORM_V7_CONTROL_TOWER_ROUTE,
  PLATFORM_V7_DATA_ROOM_ROUTE,
  PLATFORM_V7_DEALS_ROUTE,
  PLATFORM_V7_DEMO_EXECUTION_FLOW_ROUTE,
  PLATFORM_V7_DISPUTES_ROUTE,
  PLATFORM_V7_DOCUMENTS_ROUTE,
  PLATFORM_V7_EXECUTION_MAP_ROUTE,
  PLATFORM_V7_EXECUTIVE_ROUTE,
  PLATFORM_V7_FGIS_TO_LOT_ROUTE,
  PLATFORM_V7_INVESTOR_ROUTE,
  PLATFORM_V7_LOGISTICS_ROUTE,
  PLATFORM_V7_LOTS_ROUTE,
  PLATFORM_V7_LOT_CREATE_ROUTE,
  PLATFORM_V7_MARKET_RFQ_ROUTE,
  PLATFORM_V7_MONEY_ROUTE,
  PLATFORM_V7_OFFER_LOG_ROUTE,
  PLATFORM_V7_OFFER_TO_DEAL_ROUTE,
  PLATFORM_V7_OPERATOR_QUEUES_ROUTE,
  PLATFORM_V7_OPERATOR_ROUTE,
  PLATFORM_V7_PROFILE_ROUTE,
  PLATFORM_V7_PROPOSALS_ROUTE,
  PLATFORM_V7_READINESS_ROUTE,
  PLATFORM_V7_RELEASE_SAFETY_ROUTE,
  PLATFORM_V7_REPORTS_ROUTE,
  PLATFORM_V7_ROLES_ROUTE,
  PLATFORM_V7_SELLER_BATCHES_ROUTE,
  PLATFORM_V7_SELLER_BATCH_NEW_ROUTE,
  PLATFORM_V7_SELLER_LOTS_ROUTE,
  PLATFORM_V7_SELLER_OFFERS_ROUTE,
  PLATFORM_V7_SELLER_ROUTE,
  PLATFORM_V7_SIMULATOR_ROUTE,
  PLATFORM_V7_STATUS_ROUTE,
  PLATFORM_V7_TRADING_ROUTE,
  PLATFORM_V7_TRUST_ROUTE,
} from './routes';

export type PlatformV7CommandGroup = 'Сделки' | 'Лоты' | 'Споры' | 'Разделы';

export interface PlatformV7CommandSectionItem {
  id: string;
  group: 'Разделы';
  title: string;
  subtitle: string;
  href: string;
  keywords: string;
}

export const PLATFORM_V7_COMMAND_SECTION_ITEMS: PlatformV7CommandSectionItem[] = [
  {
    id: 'sec-control',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.controlTower,
    subtitle: 'Панель оператора · показатели и приоритеты',
    href: PLATFORM_V7_CONTROL_TOWER_ROUTE,
    keywords: 'центр управления оператор показатели приоритеты control tower',
  },
  {
    id: 'sec-canonical-kpi-reconciliation',
    group: 'Разделы',
    title: 'Сверка показателей',
    subtitle: 'Сравнение текущей и эталонной формулы показателей',
    href: PLATFORM_V7_CANONICAL_RECONCILIATION_ROUTE,
    keywords: 'сверка показатели формула эталон kpi canonical reconciliation',
  },
  {
    id: 'sec-deals',
    group: 'Разделы',
    title: `Все ${PLATFORM_V7_LEXICON.nav.deals.toLowerCase()}`,
    subtitle: 'Реестр сделок с фильтрами по статусу и риску',
    href: PLATFORM_V7_DEALS_ROUTE,
    keywords: 'сделки реестр',
  },
  {
    id: 'sec-lots-requests',
    group: 'Разделы',
    title: 'Лоты и запросы',
    subtitle: 'Предсделочный контур: партии, запросы цены и предложения',
    href: PLATFORM_V7_LOTS_ROUTE,
    keywords: 'лоты запросы цены партии предложения предсделочный контур',
  },
  {
    id: 'sec-market-rfq',
    group: 'Разделы',
    title: 'Лоты, запросы и предложения',
    subtitle: 'Предсделочный контур: лоты, заявки и предложения',
    href: PLATFORM_V7_MARKET_RFQ_ROUTE,
    keywords: 'лоты заявки предложения спрос предложение предсделочный контур',
  },
  {
    id: 'sec-execution-map',
    group: 'Разделы',
    title: 'Карта исполнения сделки',
    subtitle: 'Один маршрут: товар, торги, готовность, логистика, деньги и спор',
    href: PLATFORM_V7_EXECUTION_MAP_ROUTE,
    keywords: 'карта исполнения сделки маршрут товар торги готовность логистика деньги спор доказательства',
  },
  {
    id: 'sec-trading',
    group: 'Разделы',
    title: 'Торги и ставки',
    subtitle: 'Лоты, заявки, ставки, блокеры и допуск к сделке',
    href: PLATFORM_V7_TRADING_ROUTE,
    keywords: 'торги ставки лоты заявки предложения цена допуск сделка',
  },
  {
    id: 'sec-seller-offers',
    group: 'Разделы',
    title: 'Ставки продавца',
    subtitle: 'Входящие предложения по лотам, деньги, риск и действия',
    href: PLATFORM_V7_SELLER_OFFERS_ROUTE,
    keywords: 'продавец ставки предложения лоты покупатели деньги риск встречное предложение',
  },
  {
    id: 'sec-buyer-lot',
    group: 'Разделы',
    title: 'Лот глазами покупателя',
    subtitle: 'Проверка товара, условия ставки и переход к сделке',
    href: PLATFORM_V7_BUYER_LOT_ROUTE,
    keywords: 'покупатель лот ставка предложение товар качество фгис сделка',
  },
  {
    id: 'sec-anti-bypass',
    group: 'Разделы',
    title: 'Антиобход',
    subtitle: 'Правила раскрытия сторон, контактов и удержания сделки',
    href: PLATFORM_V7_ANTI_BYPASS_ROUTE,
    keywords: 'антиобход контакты раскрытие сторон удержание сделки риск обхода',
  },
  {
    id: 'sec-offer-log',
    group: 'Разделы',
    title: 'Журнал торгов',
    subtitle: 'История ставок, изменений, проверок и выбора предложения',
    href: PLATFORM_V7_OFFER_LOG_ROUTE,
    keywords: 'журнал торгов ставки история изменения проверка предложение доказательства',
  },
  {
    id: 'sec-offer-to-deal',
    group: 'Разделы',
    title: 'Ставка → черновик сделки',
    subtitle: 'Перенос условий, раскрытие сторон и проверки перед сделкой',
    href: PLATFORM_V7_OFFER_TO_DEAL_ROUTE,
    keywords: 'ставка черновик сделки условия раскрытие сторон проверки',
  },
  {
    id: 'sec-fgis-to-lot',
    group: 'Разделы',
    title: 'ФГИС → лот',
    subtitle: 'Партия, паспорт товара, блокеры и черновик лота',
    href: PLATFORM_V7_FGIS_TO_LOT_ROUTE,
    keywords: 'фгис лот партия паспорт товара остаток качество сдиз',
  },
  {
    id: 'sec-readiness',
    group: 'Разделы',
    title: 'Готовность сделки',
    subtitle: 'ФГИС, документы, логистика, банк, спор и удержания',
    href: PLATFORM_V7_READINESS_ROUTE,
    keywords: 'готовность сделки фгис документы логистика банк спор удержания',
  },
  {
    id: 'sec-bank',
    group: 'Разделы',
    title: 'Банковый контур',
    subtitle: 'Резервы, удержания, события банка, выпуск денег',
    href: PLATFORM_V7_BANK_ROUTE,
    keywords: 'банк деньги резерв удержание выпуск события',
  },
  {
    id: 'sec-release-safety',
    group: 'Разделы',
    title: 'Проверка выпуска денег',
    subtitle: 'Проверочный режим: блокеры, удержания и кандидаты к выпуску',
    href: PLATFORM_V7_RELEASE_SAFETY_ROUTE,
    keywords: 'проверка деньги выпуск удержания блокеры банк',
  },
  {
    id: 'sec-data-room',
    group: 'Разделы',
    title: 'Пакет проверки',
    subtitle: 'Проверочный пакет для банка и инвестора',
    href: PLATFORM_V7_DATA_ROOM_ROUTE,
    keywords: 'пакет проверки банк инвестор документы проверка',
  },
  {
    id: 'sec-disputes',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.disputes,
    subtitle: 'Открытые споры и удержания',
    href: PLATFORM_V7_DISPUTES_ROUTE,
    keywords: 'споры удержания',
  },
  {
    id: 'sec-logistics',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.logistics,
    subtitle: 'Маршруты, сроки прибытия, отклонения',
    href: PLATFORM_V7_LOGISTICS_ROUTE,
    keywords: 'логистика маршруты сроки прибытия отклонения',
  },
  {
    id: 'sec-integrations',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.connectors,
    subtitle: 'ФГИС, СберБизнес, СПАРК, лаборатории',
    href: PLATFORM_V7_CONNECTORS_ROUTE,
    keywords: 'интеграции фгис сбер спарк лаборатории',
  },
  {
    id: 'sec-operator',
    group: 'Разделы',
    title: 'Кабинет оператора',
    subtitle: 'Очереди, события банка, ручные действия',
    href: PLATFORM_V7_OPERATOR_ROUTE,
    keywords: 'оператор очереди ручные действия',
  },
  {
    id: 'sec-investor',
    group: 'Разделы',
    title: 'Инвестор',
    subtitle: 'Портфель сделок, риски, деньги и проверочный пакет',
    href: PLATFORM_V7_INVESTOR_ROUTE,
    keywords: 'инвестор портфель сделки деньги риск проверка',
  },
  {
    id: 'sec-roles',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.roles,
    subtitle: 'Сменить активную роль',
    href: PLATFORM_V7_ROLES_ROUTE,
    keywords: 'роли смена кабинет',
  },
  {
    id: 'sec-lot-create',
    group: 'Разделы',
    title: 'Создать лот',
    subtitle: 'Публикация новой партии в предсделочный контур',
    href: PLATFORM_V7_LOT_CREATE_ROUTE,
    keywords: 'лот создать партия публикация',
  },
  {
    id: 'sec-seller',
    group: 'Разделы',
    title: 'Кабинет продавца',
    subtitle: 'Партии, документы и причина остановки выплаты',
    href: PLATFORM_V7_SELLER_ROUTE,
    keywords: 'продавец кабинет партии',
  },
  {
    id: 'sec-seller-batches',
    group: 'Разделы',
    title: 'Партии продавца',
    subtitle: 'Реестр партий продавца',
    href: PLATFORM_V7_SELLER_BATCHES_ROUTE,
    keywords: 'партии продавца реестр',
  },
  {
    id: 'sec-seller-batch-new',
    group: 'Разделы',
    title: 'Новая партия',
    subtitle: 'Создание партии продавца',
    href: PLATFORM_V7_SELLER_BATCH_NEW_ROUTE,
    keywords: 'партия новая создать',
  },
  {
    id: 'sec-seller-lots',
    group: 'Разделы',
    title: 'Лоты продавца',
    subtitle: 'Лоты и предложения продавца',
    href: PLATFORM_V7_SELLER_LOTS_ROUTE,
    keywords: 'лоты продавца предложения',
  },
  {
    id: 'sec-buyer',
    group: 'Разделы',
    title: 'Кабинет покупателя',
    subtitle: 'Запрос, резерв и контур закупки',
    href: PLATFORM_V7_BUYER_ROUTE,
    keywords: 'покупатель кабинет закупка',
  },
  {
    id: 'sec-buyer-rfq',
    group: 'Разделы',
    title: 'Запросы на закупку',
    subtitle: 'Реестр запросов покупателя',
    href: PLATFORM_V7_BUYER_RFQ_ROUTE,
    keywords: 'запрос закупка rfq',
  },
  {
    id: 'sec-buyer-rfq-new',
    group: 'Разделы',
    title: 'Новый запрос на закупку',
    subtitle: 'Создание запроса цены',
    href: PLATFORM_V7_BUYER_RFQ_NEW_ROUTE,
    keywords: 'запрос новый rfq создать',
  },
  {
    id: 'sec-proposals',
    group: 'Разделы',
    title: 'Предложения',
    subtitle: 'Встречные предложения по лотам и запросам',
    href: PLATFORM_V7_PROPOSALS_ROUTE,
    keywords: 'предложения встречные ставки',
  },
  {
    id: 'sec-money',
    group: 'Разделы',
    title: 'Деньги',
    subtitle: 'Резерв, удержание и банковская проверка выплаты',
    href: PLATFORM_V7_MONEY_ROUTE,
    keywords: 'деньги резерв удержание выплата',
  },
  {
    id: 'sec-documents',
    group: 'Разделы',
    title: 'Документы',
    subtitle: 'Матрица документов и основания',
    href: PLATFORM_V7_DOCUMENTS_ROUTE,
    keywords: 'документы матрица основания',
  },
  {
    id: 'sec-bank-clean',
    group: 'Разделы',
    title: 'Банк · чистая сделка',
    subtitle: 'Банковый разбор сделки без блокеров',
    href: PLATFORM_V7_BANK_CLEAN_ROUTE,
    keywords: 'банк чистая сделка',
  },
  {
    id: 'sec-bank-events',
    group: 'Разделы',
    title: 'Банковские события',
    subtitle: 'Журнал банковских событий',
    href: PLATFORM_V7_BANK_EVENTS_ROUTE,
    keywords: 'банк события журнал',
  },
  {
    id: 'sec-bank-payment-basis',
    group: 'Разделы',
    title: 'Передать основание банку',
    subtitle: 'Основание выплаты для банковской проверки',
    href: PLATFORM_V7_BANK_PAYMENT_BASIS_ROUTE,
    keywords: 'банк основание выплата передача',
  },
  {
    id: 'sec-bank-factoring',
    group: 'Разделы',
    title: 'Факторинг',
    subtitle: 'Банковый модуль факторинга',
    href: PLATFORM_V7_BANK_FACTORING_ROUTE,
    keywords: 'банк факторинг',
  },
  {
    id: 'sec-bank-escrow',
    group: 'Разделы',
    title: 'Эскроу',
    subtitle: 'Удержание и выпуск средств по условиям',
    href: PLATFORM_V7_BANK_ESCROW_ROUTE,
    keywords: 'банк эскроу удержание',
  },
  {
    id: 'sec-auth',
    group: 'Разделы',
    title: 'Вход',
    subtitle: 'Вход и выбор роли',
    href: PLATFORM_V7_AUTH_ROUTE,
    keywords: 'вход авторизация роль',
  },
  {
    id: 'sec-status',
    group: 'Разделы',
    title: 'Статус платформы',
    subtitle: 'Состояние контуров и подключений',
    href: PLATFORM_V7_STATUS_ROUTE,
    keywords: 'статус платформа подключения',
  },
  {
    id: 'sec-profile',
    group: 'Разделы',
    title: 'Профиль',
    subtitle: 'Профиль организации и доступы',
    href: PLATFORM_V7_PROFILE_ROUTE,
    keywords: 'профиль организация доступы',
  },
  {
    id: 'sec-operator-queues',
    group: 'Разделы',
    title: 'Очереди оператора',
    subtitle: 'Операционные очереди и блокеры',
    href: PLATFORM_V7_OPERATOR_QUEUES_ROUTE,
    keywords: 'оператор очереди блокеры',
  },
  {
    id: 'sec-executive',
    group: 'Разделы',
    title: 'Кабинет руководителя',
    subtitle: 'Сигналы по деньгам, рискам и узким местам',
    href: PLATFORM_V7_EXECUTIVE_ROUTE,
    keywords: 'руководитель сигналы риски',
  },
  {
    id: 'sec-trust',
    group: 'Разделы',
    title: 'Доверие и безопасность',
    subtitle: 'Контур доверия и проверок',
    href: PLATFORM_V7_TRUST_ROUTE,
    keywords: 'доверие безопасность проверки',
  },
  {
    id: 'sec-simulator',
    group: 'Разделы',
    title: 'Симулятор исполнения',
    subtitle: 'Прогон сценария исполнения сделки',
    href: PLATFORM_V7_SIMULATOR_ROUTE,
    keywords: 'симулятор сценарий прогон',
  },
  {
    id: 'sec-demo-execution-flow',
    group: 'Разделы',
    title: 'Цепочка исполнения',
    subtitle: 'Обзор цепочки исполнения сделки',
    href: PLATFORM_V7_DEMO_EXECUTION_FLOW_ROUTE,
    keywords: 'цепочка исполнение обзор',
  },
  {
    id: 'sec-reports',
    group: 'Разделы',
    title: 'Отчёты',
    subtitle: 'Отчёты по исполнению и контуру',
    href: PLATFORM_V7_REPORTS_ROUTE,
    keywords: 'отчёты выгрузки',
  },
  {
    id: 'sec-ai',
    group: 'Разделы',
    title: 'AI-помощник',
    subtitle: 'AI-помощник и навигация по платформе',
    href: PLATFORM_V7_AI_ROUTE,
    keywords: 'ai помощник ассистент поиск',
  },
];

export function platformV7CommandSectionItems(): PlatformV7CommandSectionItem[] {
  return PLATFORM_V7_COMMAND_SECTION_ITEMS;
}
