import { PLATFORM_V7_LEXICON } from './lexicon';
import {
  PLATFORM_V7_ANTI_BYPASS_ROUTE,
  PLATFORM_V7_BANK_ROUTE,
  PLATFORM_V7_BUYER_LOT_ROUTE,
  PLATFORM_V7_CANONICAL_RECONCILIATION_ROUTE,
  PLATFORM_V7_CONNECTORS_ROUTE,
  PLATFORM_V7_CONTROL_TOWER_ROUTE,
  PLATFORM_V7_DATA_ROOM_ROUTE,
  PLATFORM_V7_DEALS_ROUTE,
  PLATFORM_V7_DISPUTES_ROUTE,
  PLATFORM_V7_EXECUTION_MAP_ROUTE,
  PLATFORM_V7_FGIS_TO_LOT_ROUTE,
  PLATFORM_V7_INVESTOR_ROUTE,
  PLATFORM_V7_LOGISTICS_ROUTE,
  PLATFORM_V7_LOTS_ROUTE,
  PLATFORM_V7_MARKET_RFQ_ROUTE,
  PLATFORM_V7_OFFER_LOG_ROUTE,
  PLATFORM_V7_OFFER_TO_DEAL_ROUTE,
  PLATFORM_V7_OPERATOR_ROUTE,
  PLATFORM_V7_READINESS_ROUTE,
  PLATFORM_V7_RELEASE_SAFETY_ROUTE,
  PLATFORM_V7_ROLES_ROUTE,
  PLATFORM_V7_SELLER_OFFERS_ROUTE,
  PLATFORM_V7_TRADING_ROUTE,
} from './routes';

export type PlatformV7CommandGroup = 'Сделки' | 'Лоты' | 'Споры' | 'Разделы';

export interface PlatformV7CommandSectionItem {
  id: string;
  group: 'Разделы';
  title: string;
  subtitle: string;
  href: string;
  keywords: string;
}

export const PLATFORM_V7_COMMAND_SECTION_ITEMS: PlatformV7CommandSectionItem[] = [
  {
    id: 'sec-control',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.controlTower,
    subtitle: 'Панель оператора · показатели и приоритеты',
    href: PLATFORM_V7_CONTROL_TOWER_ROUTE,
    keywords: 'центр управления оператор показатели приоритеты',
  },
  {
    id: 'sec-canonical-kpi-reconciliation',
    group: 'Разделы',
    title: 'Сверка показателей',
    subtitle: 'Сравнение текущей и эталонной формулы показателей',
    href: PLATFORM_V7_CANONICAL_RECONCILIATION_ROUTE,
    keywords: 'сверка показатели формула эталон kpi',
  },
  {
    id: 'sec-deals',
    group: 'Разделы',
    title: `Все ${PLATFORM_V7_LEXICON.nav.deals.toLowerCase()}`,
    subtitle: 'Реестр сделок с фильтрами по статусу и риску',
    href: PLATFORM_V7_DEALS_ROUTE,
    keywords: 'сделки реестр',
  },
  {
    id: 'sec-lots-requests',
    group: 'Разделы',
    title: 'Лоты и запросы',
    subtitle: 'Предсделочный контур: партии, запросы цены и предложения',
    href: PLATFORM_V7_LOTS_ROUTE,
    keywords: 'лоты запросы цены партии предложения предсделочный контур',
  },
  {
    id: 'sec-market-rfq',
    group: 'Разделы',
    title: 'Лоты, запросы и предложения',
    subtitle: 'Предсделочный контур: лоты, заявки и предложения',
    href: PLATFORM_V7_MARKET_RFQ_ROUTE,
    keywords: 'лоты заявки предложения спрос предложение предсделочный контур',
  },
  {
    id: 'sec-execution-map',
    group: 'Разделы',
    title: 'Карта исполнения сделки',
    subtitle: 'Один маршрут: товар, торги, готовность, логистика, деньги и спор',
    href: PLATFORM_V7_EXECUTION_MAP_ROUTE,
    keywords: 'карта исполнения сделки маршрут товар торги готовность логистика деньги спор доказательства',
  },
  {
    id: 'sec-trading',
    group: 'Разделы',
    title: 'Торги и ставки',
    subtitle: 'Лоты, заявки, ставки, блокеры и допуск к сделке',
    href: PLATFORM_V7_TRADING_ROUTE,
    keywords: 'торги ставки лоты заявки предложения цена допуск сделка',
  },
  {
    id: 'sec-seller-offers',
    group: 'Разделы',
    title: 'Ставки продавца',
    subtitle: 'Входящие предложения по лотам, деньги, риск и действия',
    href: PLATFORM_V7_SELLER_OFFERS_ROUTE,
    keywords: 'продавец ставки предложения лоты покупатели деньги риск встречное предложение',
  },
  {
    id: 'sec-buyer-lot',
    group: 'Разделы',
    title: 'Лот глазами покупателя',
    subtitle: 'Проверка товара, условия ставки и переход к сделке',
    href: PLATFORM_V7_BUYER_LOT_ROUTE,
    keywords: 'покупатель лот ставка предложение товар качество фгис сделка',
  },
  {
    id: 'sec-anti-bypass',
    group: 'Разделы',
    title: 'Антиобход',
    subtitle: 'Правила раскрытия сторон, контактов и удержания сделки',
    href: PLATFORM_V7_ANTI_BYPASS_ROUTE,
    keywords: 'антиобход контакты раскрытие сторон удержание сделки риск обхода',
  },
  {
    id: 'sec-offer-log',
    group: 'Разделы',
    title: 'Журнал торгов',
    subtitle: 'История ставок, изменений, проверок и выбора предложения',
    href: PLATFORM_V7_OFFER_LOG_ROUTE,
    keywords: 'журнал торгов ставки история изменения проверка предложение доказательства',
  },
  {
    id: 'sec-offer-to-deal',
    group: 'Разделы',
    title: 'Ставка → черновик сделки',
    subtitle: 'Перенос условий, раскрытие сторон и проверки перед сделкой',
    href: PLATFORM_V7_OFFER_TO_DEAL_ROUTE,
    keywords: 'ставка черновик сделки условия раскрытие сторон проверки',
  },
  {
    id: 'sec-fgis-to-lot',
    group: 'Разделы',
    title: 'ФГИС → лот',
    subtitle: 'Партия, паспорт товара, блокеры и черновик лота',
    href: PLATFORM_V7_FGIS_TO_LOT_ROUTE,
    keywords: 'фгис лот партия паспорт товара остаток качество сдиз',
  },
  {
    id: 'sec-readiness',
    group: 'Разделы',
    title: 'Готовность сделки',
    subtitle: 'ФГИС, документы, логистика, банк, спор и удержания',
    href: PLATFORM_V7_READINESS_ROUTE,
    keywords: 'готовность сделки фгис документы логистика банк спор удержания',
  },
  {
    id: 'sec-bank',
    group: 'Разделы',
    title: 'Банковый контур',
    subtitle: 'Резервы, удержания, события банка, выпуск денег',
    href: PLATFORM_V7_BANK_ROUTE,
    keywords: 'банк деньги резерв удержание выпуск события',
  },
  {
    id: 'sec-release-safety',
    group: 'Разделы',
    title: 'Проверка выпуска денег',
    subtitle: 'Проверочный режим: блокеры, удержания и кандидаты к выпуску',
    href: PLATFORM_V7_RELEASE_SAFETY_ROUTE,
    keywords: 'проверка деньги выпуск удержания блокеры банк',
  },
  {
    id: 'sec-data-room',
    group: 'Разделы',
    title: 'Пакет проверки',
    subtitle: 'Проверочный пакет для банка и инвестора',
    href: PLATFORM_V7_DATA_ROOM_ROUTE,
    keywords: 'пакет проверки банк инвестор документы проверка',
  },
  {
    id: 'sec-disputes',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.disputes,
    subtitle: 'Открытые споры и удержания',
    href: PLATFORM_V7_DISPUTES_ROUTE,
    keywords: 'споры удержания',
  },
  {
    id: 'sec-logistics',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.logistics,
    subtitle: 'Маршруты, сроки прибытия, отклонения',
    href: PLATFORM_V7_LOGISTICS_ROUTE,
    keywords: 'логистика маршруты сроки прибытия отклонения',
  },
  {
    id: 'sec-integrations',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.connectors,
    subtitle: 'ФГИС, СберБизнес, СПАРК, лаборатории',
    href: PLATFORM_V7_CONNECTORS_ROUTE,
    keywords: 'интеграции фгис сбер спарк лаборатории',
  },
  {
    id: 'sec-operator',
    group: 'Разделы',
    title: 'Кабинет оператора',
    subtitle: 'Очереди, события банка, ручные действия',
    href: PLATFORM_V7_OPERATOR_ROUTE,
    keywords: 'оператор очереди ручные действия',
  },
  {
    id: 'sec-investor',
    group: 'Разделы',
    title: 'Инвестор',
    subtitle: 'Портфель сделок, риски, деньги и проверочный пакет',
    href: PLATFORM_V7_INVESTOR_ROUTE,
    keywords: 'инвестор портфель сделки деньги риск проверка',
  },
  {
    id: 'sec-roles',
    group: 'Разделы',
    title: PLATFORM_V7_LEXICON.nav.roles,
    subtitle: 'Сменить активную роль',
    href: PLATFORM_V7_ROLES_ROUTE,
    keywords: 'роли смена кабинет',
  },
  {
    id: 'sec-data-room',
    group: 'Разделы',
    title: 'Data Room',
    subtitle: 'Проверочный пакет для банка и инвестора',
    href: '/platform-v7/data-room',
    keywords: 'data room due diligence банк инвестор проверка документы',
  },
];

export function platformV7CommandSectionItems(): PlatformV7CommandSectionItem[] {
  return PLATFORM_V7_COMMAND_SECTION_ITEMS;
}
