export const PLATFORM_V7_CONTROL_TOWER_ROUTE = '/platform-v7/control-tower';
export const PLATFORM_V7_CANONICAL_RECONCILIATION_ROUTE = '/platform-v7/control-tower/canonical-reconciliation';
export const PLATFORM_V7_DEALS_ROUTE = '/platform-v7/deals';
export const PLATFORM_V7_COMMODITY_PROFILES_ROUTE = '/platform-v7/commodity-profiles';
export const PLATFORM_V7_INTEGRATIONS_ROUTE = '/platform-v7/integrations';
export const PLATFORM_V7_LOTS_ROUTE = '/platform-v7/lots';
export const PLATFORM_V7_LOT_CREATE_ROUTE = '/platform-v7/lots/create';
export const PLATFORM_V7_MARKET_RFQ_ROUTE = '/platform-v7/market-rfq';
export const PLATFORM_V7_EXECUTION_MAP_ROUTE = '/platform-v7/execution-map';
export const PLATFORM_V7_TRADING_ROUTE = '/platform-v7/trading';
export const PLATFORM_V7_DOMAIN_CORE_ROUTE = '/platform-v7/domain-core';
export const PLATFORM_V7_SELLER_ROUTE = '/platform-v7/seller';
export const PLATFORM_V7_SELLER_BATCHES_ROUTE = '/platform-v7/seller/batches';
export const PLATFORM_V7_SELLER_BATCH_NEW_ROUTE = '/platform-v7/seller/batches/new';
export const PLATFORM_V7_SELLER_LOTS_ROUTE = '/platform-v7/seller/lots';
export const PLATFORM_V7_SELLER_FGIS_PARTIES_ROUTE = '/platform-v7/seller/fgis-parties';
export const PLATFORM_V7_SELLER_OFFERS_ROUTE = '/platform-v7/seller/offers';
export const PLATFORM_V7_BUYER_ROUTE = '/platform-v7/buyer';
export const PLATFORM_V7_BUYER_RFQ_ROUTE = '/platform-v7/buyer/rfq';
export const PLATFORM_V7_BUYER_RFQ_NEW_ROUTE = '/platform-v7/buyer/rfq/new';
export const PLATFORM_V7_BUYER_LOT_ROUTE = '/platform-v7/buyer-lot';
export const PLATFORM_V7_PROPOSALS_ROUTE = '/platform-v7/proposals';
export const PLATFORM_V7_MONEY_ROUTE = '/platform-v7/money';
export const PLATFORM_V7_DOCUMENTS_ROUTE = '/platform-v7/documents';
export const PLATFORM_V7_ANTI_BYPASS_ROUTE = '/platform-v7/anti-bypass';
export const PLATFORM_V7_OFFER_LOG_ROUTE = '/platform-v7/offer-log';
export const PLATFORM_V7_OFFER_TO_DEAL_ROUTE = '/platform-v7/offer-to-deal';
export const PLATFORM_V7_FGIS_TO_LOT_ROUTE = '/platform-v7/fgis-to-lot';
export const PLATFORM_V7_READINESS_ROUTE = '/platform-v7/readiness';
export const PLATFORM_V7_BANK_ROUTE = '/platform-v7/bank';
export const PLATFORM_V7_BANK_CLEAN_ROUTE = '/platform-v7/bank/clean';
export const PLATFORM_V7_BANK_EVENTS_ROUTE = '/platform-v7/bank/events';
export const PLATFORM_V7_RELEASE_SAFETY_ROUTE = '/platform-v7/bank/release-safety';
export const PLATFORM_V7_BANK_PAYMENT_BASIS_ROUTE = '/platform-v7/bank/payment-basis';
export const PLATFORM_V7_BANK_FACTORING_ROUTE = '/platform-v7/bank/factoring';
export const PLATFORM_V7_BANK_ESCROW_ROUTE = '/platform-v7/bank/escrow';
export const PLATFORM_V7_DATA_ROOM_ROUTE = '/platform-v7/data-room';
export const PLATFORM_V7_DISPUTES_ROUTE = '/platform-v7/disputes';
export const PLATFORM_V7_LOGISTICS_ROUTE = '/platform-v7/logistics';
export const PLATFORM_V7_FIELD_ROUTE = '/platform-v7/field';
export const PLATFORM_V7_DRIVER_FIELD_ROUTE = '/platform-v7/driver/field';
export const PLATFORM_V7_SURVEYOR_ROUTE = '/platform-v7/surveyor';
export const PLATFORM_V7_ELEVATOR_ROUTE = '/platform-v7/elevator';
export const PLATFORM_V7_LAB_ROUTE = '/platform-v7/lab';
export const PLATFORM_V7_ARBITRATOR_ROUTE = '/platform-v7/arbitrator';
export const PLATFORM_V7_CONNECTORS_ROUTE = '/platform-v7/connectors';
export const PLATFORM_V7_AUTH_ROUTE = '/platform-v7/auth';
export const PLATFORM_V7_STATUS_ROUTE = '/platform-v7/status';
export const PLATFORM_V7_PROFILE_ROUTE = '/platform-v7/profile';
export const PLATFORM_V7_OPERATOR_QUEUES_ROUTE = '/platform-v7/operator-cockpit/queues';
export const PLATFORM_V7_OPERATOR_ROUTE = '/platform-v7/operator';
export const PLATFORM_V7_PROCUREMENT_ROUTE = '/platform-v7/procurement';
export const PLATFORM_V7_INVESTOR_ROUTE = '/platform-v7/investor';
export const PLATFORM_V7_EXECUTIVE_ROUTE = '/platform-v7/executive';
export const PLATFORM_V7_ROLES_ROUTE = '/platform-v7/roles';
export const PLATFORM_V7_COMPLIANCE_ROUTE = '/platform-v7/compliance';
export const PLATFORM_V7_TRUST_ROUTE = '/platform-v7/trust';
export const PLATFORM_V7_SIMULATOR_ROUTE = '/platform-v7/simulator';
export const PLATFORM_V7_DEAL_FLOW_ROUTE = '/platform-v7/deal-flow';
export const PLATFORM_V7_DEMO_EXECUTION_FLOW_ROUTE = PLATFORM_V7_DEAL_FLOW_ROUTE;
export const PLATFORM_V7_REPORTS_ROUTE = '/platform-v7/reports';
export const PLATFORM_V7_PILOT_RUNBOOK_ROUTE = '/platform-v7/pilot-runbook';
export const PLATFORM_V7_AI_ROUTE = '/platform-v7/assistant';
export const PLATFORM_V7_AI_COMPATIBILITY_ROUTE = '/platform-v7/ai';

export const PLATFORM_V7R_ROLES_ROUTE = '/platform-v7r/roles';
export const PLATFORM_V7R_DRIVER_ROUTE = '/platform-v7r/driver';
export const PLATFORM_V7R_SURVEYOR_ROUTE = '/platform-v7r/surveyor';
export const PLATFORM_V7R_ELEVATOR_ROUTE = '/platform-v7r/elevator';
export const PLATFORM_V7R_LAB_ROUTE = '/platform-v7r/lab';
export const PLATFORM_V7R_ARBITRATOR_ROUTE = '/platform-v7r/arbitrator';
export const PLATFORM_V7R_ANALYTICS_ROUTE = '/platform-v7r/analytics';

export const PLATFORM_V7_EXECUTION_MACHINE_STRIP_ROUTES = [
  PLATFORM_V7_READINESS_ROUTE,
  PLATFORM_V7_EXECUTION_MAP_ROUTE,
  PLATFORM_V7_RELEASE_SAFETY_ROUTE,
  PLATFORM_V7_BANK_PAYMENT_BASIS_ROUTE,
  PLATFORM_V7_BANK_CLEAN_ROUTE,
  PLATFORM_V7_BANK_EVENTS_ROUTE,
  PLATFORM_V7_BANK_FACTORING_ROUTE,
  PLATFORM_V7_BANK_ESCROW_ROUTE,
  PLATFORM_V7_DATA_ROOM_ROUTE,
  PLATFORM_V7_LOGISTICS_ROUTE,
  PLATFORM_V7_DISPUTES_ROUTE,
  PLATFORM_V7_MONEY_ROUTE,
  PLATFORM_V7_DOCUMENTS_ROUTE,
  PLATFORM_V7_CONNECTORS_ROUTE,
  PLATFORM_V7_INTEGRATIONS_ROUTE,
  PLATFORM_V7_TRUST_ROUTE,
  PLATFORM_V7_SIMULATOR_ROUTE,
  PLATFORM_V7_DEAL_FLOW_ROUTE,
  PLATFORM_V7_REPORTS_ROUTE,
] as const;

export const PLATFORM_V7_COMMAND_ROUTE_SURFACE = [
  PLATFORM_V7_CONTROL_TOWER_ROUTE,
  PLATFORM_V7_CANONICAL_RECONCILIATION_ROUTE,
  PLATFORM_V7_DEALS_ROUTE,
  PLATFORM_V7_COMMODITY_PROFILES_ROUTE,
  PLATFORM_V7_INTEGRATIONS_ROUTE,
  PLATFORM_V7_LOTS_ROUTE,
  PLATFORM_V7_LOT_CREATE_ROUTE,
  PLATFORM_V7_MARKET_RFQ_ROUTE,
  PLATFORM_V7_EXECUTION_MAP_ROUTE,
  PLATFORM_V7_TRADING_ROUTE,
  PLATFORM_V7_SELLER_ROUTE,
  PLATFORM_V7_SELLER_BATCHES_ROUTE,
  PLATFORM_V7_SELLER_BATCH_NEW_ROUTE,
  PLATFORM_V7_SELLER_LOTS_ROUTE,
  PLATFORM_V7_SELLER_OFFERS_ROUTE,
  PLATFORM_V7_BUYER_ROUTE,
  PLATFORM_V7_BUYER_RFQ_ROUTE,
  PLATFORM_V7_BUYER_RFQ_NEW_ROUTE,
  PLATFORM_V7_BUYER_LOT_ROUTE,
  PLATFORM_V7_PROPOSALS_ROUTE,
  PLATFORM_V7_MONEY_ROUTE,
  PLATFORM_V7_DOCUMENTS_ROUTE,
  PLATFORM_V7_ANTI_BYPASS_ROUTE,
  PLATFORM_V7_OFFER_LOG_ROUTE,
  PLATFORM_V7_OFFER_TO_DEAL_ROUTE,
  PLATFORM_V7_FGIS_TO_LOT_ROUTE,
  PLATFORM_V7_READINESS_ROUTE,
  PLATFORM_V7_BANK_ROUTE,
  PLATFORM_V7_BANK_CLEAN_ROUTE,
  PLATFORM_V7_BANK_EVENTS_ROUTE,
  PLATFORM_V7_RELEASE_SAFETY_ROUTE,
  PLATFORM_V7_BANK_PAYMENT_BASIS_ROUTE,
  PLATFORM_V7_BANK_FACTORING_ROUTE,
  PLATFORM_V7_BANK_ESCROW_ROUTE,
  PLATFORM_V7_DATA_ROOM_ROUTE,
  PLATFORM_V7_DISPUTES_ROUTE,
  PLATFORM_V7_LOGISTICS_ROUTE,
  PLATFORM_V7_CONNECTORS_ROUTE,
  PLATFORM_V7_AUTH_ROUTE,
  PLATFORM_V7_STATUS_ROUTE,
  PLATFORM_V7_PROFILE_ROUTE,
  PLATFORM_V7_OPERATOR_QUEUES_ROUTE,
  PLATFORM_V7_OPERATOR_ROUTE,
  PLATFORM_V7_INVESTOR_ROUTE,
  PLATFORM_V7_EXECUTIVE_ROUTE,
  PLATFORM_V7_ROLES_ROUTE,
  PLATFORM_V7_TRUST_ROUTE,
  PLATFORM_V7_SIMULATOR_ROUTE,
  PLATFORM_V7_DEAL_FLOW_ROUTE,
  PLATFORM_V7_REPORTS_ROUTE,
  PLATFORM_V7_AI_ROUTE,
] as const;

export const PLATFORM_V7_SHELL_ROUTE_SURFACE = [
  PLATFORM_V7_PILOT_RUNBOOK_ROUTE,
  PLATFORM_V7_CONTROL_TOWER_ROUTE,
  PLATFORM_V7_DEALS_ROUTE,
  PLATFORM_V7_COMMODITY_PROFILES_ROUTE,
  PLATFORM_V7_INTEGRATIONS_ROUTE,
  PLATFORM_V7_LOTS_ROUTE,
  PLATFORM_V7_SELLER_ROUTE,
  PLATFORM_V7_SELLER_BATCHES_ROUTE,
  PLATFORM_V7_SELLER_BATCH_NEW_ROUTE,
  PLATFORM_V7_SELLER_LOTS_ROUTE,
  PLATFORM_V7_BUYER_ROUTE,
  PLATFORM_V7_BUYER_RFQ_ROUTE,
  PLATFORM_V7_BUYER_RFQ_NEW_ROUTE,
  PLATFORM_V7_PROPOSALS_ROUTE,
  PLATFORM_V7_MONEY_ROUTE,
  PLATFORM_V7_DOCUMENTS_ROUTE,
  PLATFORM_V7_PROCUREMENT_ROUTE,
  PLATFORM_V7_LOGISTICS_ROUTE,
  PLATFORM_V7_BANK_ROUTE,
  PLATFORM_V7_BANK_CLEAN_ROUTE,
  PLATFORM_V7_BANK_EVENTS_ROUTE,
  PLATFORM_V7_RELEASE_SAFETY_ROUTE,
  PLATFORM_V7_BANK_PAYMENT_BASIS_ROUTE,
  PLATFORM_V7_BANK_FACTORING_ROUTE,
  PLATFORM_V7_BANK_ESCROW_ROUTE,
  PLATFORM_V7_DISPUTES_ROUTE,
  PLATFORM_V7_COMPLIANCE_ROUTE,
  PLATFORM_V7_FIELD_ROUTE,
  PLATFORM_V7_CONNECTORS_ROUTE,
  PLATFORM_V7_AUTH_ROUTE,
  PLATFORM_V7_STATUS_ROUTE,
  PLATFORM_V7_PROFILE_ROUTE,
  PLATFORM_V7_OPERATOR_QUEUES_ROUTE,
  PLATFORM_V7_OPERATOR_ROUTE,
  PLATFORM_V7_INVESTOR_ROUTE,
  PLATFORM_V7_EXECUTIVE_ROUTE,
  PLATFORM_V7_TRUST_ROUTE,
  PLATFORM_V7_SIMULATOR_ROUTE,
  PLATFORM_V7_DEAL_FLOW_ROUTE,
  PLATFORM_V7_REPORTS_ROUTE,
  PLATFORM_V7_DRIVER_FIELD_ROUTE,
  PLATFORM_V7_SURVEYOR_ROUTE,
  PLATFORM_V7_ELEVATOR_ROUTE,
  PLATFORM_V7_LAB_ROUTE,
  PLATFORM_V7_ARBITRATOR_ROUTE,
  PLATFORM_V7_AI_ROUTE,
  PLATFORM_V7R_ROLES_ROUTE,
  PLATFORM_V7R_DRIVER_ROUTE,
  PLATFORM_V7R_SURVEYOR_ROUTE,
  PLATFORM_V7R_ELEVATOR_ROUTE,
  PLATFORM_V7R_LAB_ROUTE,
  PLATFORM_V7R_ARBITRATOR_ROUTE,
  PLATFORM_V7R_ANALYTICS_ROUTE,
] as const;

export type PlatformV7ExecutionMachineStripRoute = typeof PLATFORM_V7_EXECUTION_MACHINE_STRIP_ROUTES[number];
export type PlatformV7CommandRouteSurface = typeof PLATFORM_V7_COMMAND_ROUTE_SURFACE[number];
export type PlatformV7ShellRouteSurface = typeof PLATFORM_V7_SHELL_ROUTE_SURFACE[number];
