import type { SupportCase, SupportCategory, SupportMessage, SupportPriority, SupportRelatedEntityType, SupportStatus } from './support-types';

export const SUPPORT_CATEGORY_LABELS: Record<SupportCategory, string> = { money: 'Деньги', documents: 'Документы', logistics: 'Логистика', acceptance: 'Приёмка', quality: 'Качество', dispute: 'Спор', access: 'Доступ', integration: 'Интеграция', other: 'Другое' };
export const SUPPORT_PRIORITY_LABELS: Record<SupportPriority, string> = { P0: 'Критично', P1: 'Высоко', P2: 'Обычно', P3: 'Справка' };
export const SUPPORT_STATUS_LABELS: Record<SupportStatus, string> = { created: 'Создано', accepted: 'Принято в работу', waiting_user: 'Нужны данные', waiting_external: 'Ожидается внешнее действие', assigned_operator: 'Назначен оператор', assigned_bank: 'Передано в банк', assigned_logistics: 'Передано в логистику', resolved: 'Решение подготовлено', closed: 'Закрыто', escalated: 'Эскалировано' };
export const SUPPORT_ENTITY_LABELS: Record<SupportRelatedEntityType, string> = { deal: 'Сделка', lot: 'Лот', trip: 'Рейс', document: 'Документ', blocker: 'Блокер', dispute: 'Спор', money: 'Деньги', integration: 'Интеграция', other: 'Объект' };

export function supportFormatRub(value: number): string { return new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 }).format(value) + ' ₽'; }
export function supportSlaHours(priority: SupportPriority): number { return priority === 'P0' ? 2 : priority === 'P1' ? 8 : priority === 'P2' ? 24 : 72; }
export function supportOwner(category: SupportCategory): string { return category === 'money' || category === 'dispute' ? 'Банковый контур' : category === 'logistics' ? 'Логистика' : category === 'documents' ? 'Документы' : category === 'acceptance' ? 'Приёмка' : category === 'quality' ? 'Качество' : category === 'access' ? 'Доступ' : category === 'integration' ? 'Интеграции' : 'Оператор сделки'; }
export function supportStatusByOwner(owner: string): SupportStatus { return owner === 'Банковый контур' ? 'assigned_bank' : owner === 'Логистика' ? 'assigned_logistics' : 'assigned_operator'; }
export function supportObjectLabel(item: Pick<SupportCase, 'relatedEntityType' | 'relatedEntityId'>): string { return `${SUPPORT_ENTITY_LABELS[item.relatedEntityType]} ${item.relatedEntityId}`; }
export function supportSortCases(cases: SupportCase[]): SupportCase[] { const rank = { P0: 0, P1: 1, P2: 2, P3: 3 }; return [...cases].sort((a, b) => rank[a.priority] - rank[b.priority] || new Date(a.slaDueAt).getTime() - new Date(b.slaDueAt).getTime()); }
export function supportLastMessage(caseId: string, messages: SupportMessage[]): string { return messages.filter((m) => m.caseId === caseId && m.public).at(-1)?.body ?? 'Ответ ещё не добавлен.'; }
export function supportSlaDueAt(priority: SupportPriority, now: string): string { return new Date(new Date(now).getTime() + supportSlaHours(priority) * 3600000).toISOString(); }
export function supportCategoryByText(text: string): SupportCategory { const value = text.toLowerCase(); if (/(деньг|оплат|выпуск|удерж|резерв|банк|сумм)/i.test(value)) return 'money'; if (/(документ|сдиз|эдо|наклад|акт|пакет)/i.test(value)) return 'documents'; if (/(рейс|водител|маршрут|машин|логист|груз)/i.test(value)) return 'logistics'; if (/(при[её]мк|вес|разгруз|элеватор)/i.test(value)) return 'acceptance'; if (/(качеств|лаборатор|проб|класс)/i.test(value)) return 'quality'; if (/(спор|претенз|арбитр|доказательств)/i.test(value)) return 'dispute'; if (/(доступ|роль|войти|кабинет|права)/i.test(value)) return 'access'; if (/(интеграц|фгис|есиа|внешн)/i.test(value)) return 'integration'; return 'other'; }
export function supportPriority(category: SupportCategory, moneyAtRiskRub: number, text: string): SupportPriority { const hard = /(заблок|останов|не выпуск|не закрыт|спор|отклон|удерж)/i.test(text); if (hard && (moneyAtRiskRub > 0 || ['money', 'logistics', 'acceptance', 'dispute'].includes(category))) return 'P0'; if (['documents', 'logistics', 'access', 'integration'].includes(category)) return 'P1'; return 'P2'; }
