import type {
  Dispute,
  DocumentRequirement,
  ElevatorOperation,
  EvidencePack,
  GrainBatch,
  GrainQualityProfile,
  LogisticsIncident,
  LogisticsOrder,
  MarketLot,
  Offer,
  QualityDelta,
  RFQ,
  SampleChain,
  SdizGate,
  WeightBalance,
} from './types';
import { money } from './format';
import { calculateBatchReadiness } from './automation/readiness-engine';
import { calculateQualityDelta } from './automation/quality-delta-engine';
import { calculateWeightBalance } from './automation/weight-balance-engine';

const now = '2026-05-05T09:00:00.000Z';

export const grainBatches: GrainBatch[] = [
  {
    id: 'GB-450-TMB-01',
    ownerId: 'SELLER-01',
    ownerName: 'КФХ Петров',
    ownerInn: '6829000001',
    ownerRole: 'seller',
    crop: 'Пшеница',
    gostClass: '4 класс',
    harvestYear: 2025,
    totalVolumeTons: 450,
    availableVolumeTons: 320,
    reservedVolumeTons: 130,
    soldVolumeTons: 0,
    storageType: 'farm_storage',
    storageLocationName: 'Склад хозяйства №2',
    region: 'Тамбовская область',
    address: 'Тамбовская область, Моршанский район',
    fgisPartyId: 'FGIS-SBX-GB-450',
    fgisBatchId: 'FGIS-SBX-2026-000450',
    sdizNumber: 'СДИЗ-SBX-240-01',
    fgisStatus: 'linked',
    qualityProfileId: 'QP-SELLER-01',
    documentReadinessId: 'DOC-GB-450',
    readinessScore: 82,
    blockers: [],
    maturity: 'sandbox',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'GB-210-VRN-02',
    ownerId: 'SELLER-02',
    ownerName: 'ООО Агро Север',
    ownerRole: 'seller',
    crop: 'Ячмень',
    gostClass: '2 класс',
    harvestYear: 2025,
    totalVolumeTons: 210,
    availableVolumeTons: 210,
    reservedVolumeTons: 0,
    soldVolumeTons: 0,
    storageType: 'elevator',
    storageLocationName: 'Элеватор Рассказово',
    region: 'Воронежская область',
    fgisStatus: 'manual_mode',
    readinessScore: 58,
    blockers: [],
    maturity: 'manual',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'GB-680-KRS-03',
    ownerId: 'SELLER-03',
    ownerName: 'СПК Колос',
    ownerRole: 'seller',
    crop: 'Пшеница',
    gostClass: '3 класс',
    harvestYear: 2025,
    totalVolumeTons: 680,
    availableVolumeTons: 680,
    reservedVolumeTons: 0,
    soldVolumeTons: 0,
    storageType: 'warehouse',
    storageLocationName: 'Склад №4',
    region: 'Курская область',
    fgisStatus: 'sync_error',
    qualityProfileId: 'QP-SELLER-03',
    readinessScore: 66,
    blockers: [],
    maturity: 'sandbox',
    createdAt: now,
    updatedAt: now,
  },
];

export const qualityProfiles: GrainQualityProfile[] = [
  {
    id: 'QP-SELLER-01',
    source: 'seller_declared',
    crop: 'Пшеница',
    gostClass: '4 класс',
    moisture: 13.5,
    protein: 12.6,
    gluten: 23,
    idk: 82,
    natWeight: 760,
    fallingNumber: 265,
    weedImpurity: 2,
    grainImpurity: 5,
    labName: 'Лаборатория продавца',
    measuredAt: now,
    maturity: 'manual',
  },
  {
    id: 'QP-ELEVATOR-01',
    source: 'elevator_lab',
    crop: 'Пшеница',
    gostClass: '4 класс',
    moisture: 14.6,
    protein: 12.1,
    gluten: 20,
    idk: 91,
    natWeight: 742,
    fallingNumber: 248,
    weedImpurity: 3.1,
    grainImpurity: 5.7,
    labName: 'Элеваторная лаборатория',
    labProtocolId: 'LAB-SBX-777',
    measuredAt: now,
    maturity: 'sandbox',
  },
  {
    id: 'QP-SELLER-03',
    source: 'seller_declared',
    crop: 'Пшеница',
    gostClass: '3 класс',
    moisture: 13.1,
    protein: 13.4,
    gluten: 25,
    natWeight: 775,
    weedImpurity: 1.8,
    maturity: 'manual',
  },
];

export const documents: DocumentRequirement[] = [
  {
    id: 'DOC-CONTRACT-01',
    dealId: 'DL-GRAIN-450',
    relatedEntityType: 'deal',
    relatedEntityId: 'DL-GRAIN-450',
    documentType: 'contract',
    required: true,
    status: 'signed',
    responsibleRole: 'seller',
    blocksLotPublication: false,
    blocksShipment: false,
    blocksAcceptance: false,
    blocksMoneyRelease: false,
    externalSystem: 'edo',
    externalStatus: 'тестовый статус подписи',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'DOC-SDIZ-TR-01',
    dealId: 'DL-GRAIN-450',
    relatedEntityType: 'logistics',
    relatedEntityId: 'LOG-450-01',
    documentType: 'sdiz_transportation',
    required: true,
    status: 'manual_review',
    responsibleRole: 'seller',
    blocksLotPublication: false,
    blocksShipment: true,
    blocksAcceptance: true,
    blocksMoneyRelease: true,
    externalSystem: 'fgis',
    externalStatus: 'требует боевого подключения',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'DOC-QUALITY-01',
    dealId: 'DL-GRAIN-450',
    relatedEntityType: 'lab',
    relatedEntityId: 'LAB-SBX-777',
    documentType: 'quality_protocol',
    required: true,
    status: 'uploaded',
    responsibleRole: 'lab',
    blocksLotPublication: false,
    blocksShipment: false,
    blocksAcceptance: false,
    blocksMoneyRelease: false,
    externalSystem: 'manual',
    createdAt: now,
    updatedAt: now,
  },
];

export const sdizGates: SdizGate[] = [
  {
    id: 'SDIZ-REAL-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    basis: 'CPT',
    operationType: 'realization',
    responsibleRole: 'seller',
    responsiblePartyId: 'SELLER-01',
    required: true,
    status: 'signed',
    sdizNumber: 'СДИЗ-SBX-240-01',
    expectedVolumeTons: 240,
    actualVolumeTons: 240,
    blockingLotPublication: false,
    blockingDealCreation: false,
    blockingShipment: false,
    blockingAcceptance: false,
    blockingMoneyRelease: false,
    maturity: 'sandbox',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'SDIZ-TRANSPORT-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    logisticsOrderId: 'LOG-450-01',
    routeLegId: 'RL-450-01',
    basis: 'CPT',
    operationType: 'transportation',
    responsibleRole: 'seller',
    responsiblePartyId: 'SELLER-01',
    required: true,
    status: 'manual_review',
    expectedVolumeTons: 240,
    actualVolumeTons: 238.7,
    blockingLotPublication: false,
    blockingDealCreation: false,
    blockingShipment: false,
    blockingAcceptance: true,
    blockingMoneyRelease: true,
    errorMessage: 'Погашение СДИЗ перевозки требует проверки в тестовом контуре.',
    maturity: 'sandbox',
    createdAt: now,
    updatedAt: now,
  },
];

export const rfqs: RFQ[] = [
  {
    id: 'RFQ-1000-001',
    buyerId: 'BUYER-01',
    buyerName: 'Мукомольный комбинат Центр',
    buyerInn: '7700000001',
    crop: 'Пшеница',
    gostClass: '4 класс',
    volumeTons: 1000,
    minVolumeTons: 200,
    maxPricePerTon: money(15100),
    basis: 'CPT',
    deliveryLocationName: 'Завод покупателя',
    deliveryRegion: 'Московская область',
    deliveryDateFrom: '2026-05-10T00:00:00.000Z',
    deliveryDateTo: '2026-05-20T00:00:00.000Z',
    qualityRequirements: { maxMoisture: 14, minProtein: 12, minGluten: 20, minNatWeight: 740, maxWeedImpurity: 3 },
    paymentTerms: 'after_acceptance',
    paymentDelayDays: 2,
    requiresLogistics: true,
    requiresIndependentLab: false,
    requiresBankReserve: true,
    documentRequirements: ['договор', 'СДИЗ', 'протокол качества', 'весовые документы', 'УПД'],
    status: 'matching',
    maturity: 'sandbox',
    createdAt: now,
    expiresAt: '2026-05-12T12:00:00.000Z',
  },
];

const readiness = calculateBatchReadiness(grainBatches[0], documents, sdizGates);

export const marketLots: MarketLot[] = [
  {
    id: 'LOT-GB-450-01',
    batchId: 'GB-450-TMB-01',
    passportId: 'LP-GB-450-01',
    sellerId: 'SELLER-01',
    crop: 'Пшеница',
    gostClass: '4 класс',
    volumeTons: 240,
    basis: 'CPT',
    pricePerTon: money(14850),
    minimumPricePerTon: money(14400),
    shipmentWindowFrom: '2026-05-08T00:00:00.000Z',
    shipmentWindowTo: '2026-05-13T00:00:00.000Z',
    status: 'offer_received',
    readiness,
    netbackCalculationIds: ['NB-OFFER-01', 'NB-OFFER-02'],
    maturity: 'sandbox',
    createdAt: now,
    updatedAt: now,
  },
];

export const offers: Offer[] = [
  {
    id: 'OFF-01',
    type: 'rfq_response',
    marketLotId: 'LOT-GB-450-01',
    rfqId: 'RFQ-1000-001',
    batchId: 'GB-450-TMB-01',
    sellerId: 'SELLER-01',
    buyerId: 'BUYER-01',
    crop: 'Пшеница',
    volumeTons: 240,
    pricePerTon: money(14850),
    basis: 'CPT',
    paymentTerms: 'after_acceptance',
    logisticsOption: 'platform_logistics',
    qualitySnapshotId: 'QP-SELLER-01',
    status: 'leading',
    expiresAt: '2026-05-07T12:00:00.000Z',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'OFF-02',
    type: 'lot_bid',
    marketLotId: 'LOT-GB-450-01',
    batchId: 'GB-450-TMB-01',
    sellerId: 'SELLER-01',
    buyerId: 'BUYER-02',
    crop: 'Пшеница',
    volumeTons: 240,
    pricePerTon: money(15150),
    basis: 'EXW',
    paymentTerms: 'after_documents',
    logisticsOption: 'buyer_pickup',
    qualitySnapshotId: 'QP-SELLER-01',
    status: 'submitted',
    expiresAt: '2026-05-07T12:00:00.000Z',
    createdAt: now,
    updatedAt: now,
  },
];

export const logisticsIncidents: LogisticsIncident[] = [
  {
    id: 'INC-WEIGHT-01',
    dealId: 'DL-GRAIN-450',
    logisticsOrderId: 'LOG-450-01',
    type: 'weight_deviation',
    severity: 'warning',
    title: 'Весовое расхождение выше допуска',
    moneyImpact: money(50034),
    status: 'open',
    createdAt: now,
  },
];

export const logisticsOrders: LogisticsOrder[] = [
  {
    id: 'LOG-450-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    cargo: 'Пшеница 4 класс',
    volumeTons: 240,
    originName: 'Склад хозяйства №2',
    originRegion: 'Тамбовская область',
    destinationName: 'Завод покупателя',
    destinationRegion: 'Московская область',
    basis: 'CPT',
    plannedLoadWindowFrom: '2026-05-08T08:00:00.000Z',
    plannedLoadWindowTo: '2026-05-08T14:00:00.000Z',
    plannedDeliveryWindowFrom: '2026-05-09T08:00:00.000Z',
    plannedDeliveryWindowTo: '2026-05-09T18:00:00.000Z',
    carrierId: 'CARRIER-01',
    carrierName: 'Федеральный перевозчик АгроТранс',
    vehiclePlate: 'А123ВС68',
    trailerPlate: 'В456МР68',
    driverId: 'DRIVER-01',
    driverName: 'Иван Соколов',
    status: 'arrived',
    transportPackId: 'TP-450-01',
    routeLegIds: ['RL-450-01'],
    incidentIds: ['INC-WEIGHT-01'],
    maturity: 'sandbox',
    createdAt: now,
    updatedAt: now,
  },
];

export const sampleChains: SampleChain[] = [
  {
    id: 'SAMPLE-450-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    logisticsOrderId: 'LOG-450-01',
    routeLegId: 'RL-450-01',
    elevatorOperationId: 'EL-OP-450-01',
    status: 'protocol_ready',
    takenAt: now,
    takenByRole: 'elevator',
    takenByName: 'Смена элеватора №3',
    takenLocation: 'Элеватор Рассказово',
    sealNumber: 'PL-778812',
    photoIds: ['PHOTO-SEAL-01', 'PHOTO-SAMPLE-01'],
    labId: 'LAB-01',
    labName: 'Элеваторная лаборатория',
    labReceivedAt: now,
    labProtocolId: 'LAB-SBX-777',
    repeatAllowed: true,
    arbitrationSampleExists: true,
    arbitrationStatus: 'not_requested',
    evidencePackId: 'EVP-450-01',
    createdAt: now,
    updatedAt: now,
  },
];

export const weightBalances: WeightBalance[] = [
  calculateWeightBalance({
    id: 'WB-450-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    logisticsOrderId: 'LOG-450-01',
    routeLegId: 'RL-450-01',
    elevatorOperationId: 'EL-OP-450-01',
    contractedVolumeTons: 240,
    loadedGrossTons: 253.6,
    loadedTareTons: 14.2,
    receivedGrossTons: 252.8,
    receivedTareTons: 14.1,
    acceptedNetTons: 236.9,
    tolerancePercent: 0.5,
    pricePerTon: money(14850),
    evidenceIds: ['PHOTO-WEIGHT-01'],
    createdAt: now,
    updatedAt: now,
  }),
];

export const qualityDeltas: QualityDelta[] = [
  calculateQualityDelta({
    id: 'QD-450-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    agreedQualityProfile: qualityProfiles[0],
    acceptedQualityProfile: qualityProfiles[1],
    pricePerTon: money(14850),
    volumeTons: 240,
    createdAt: now,
    updatedAt: now,
  }),
];

export const elevatorOperations: ElevatorOperation[] = [
  {
    id: 'EL-OP-450-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    logisticsOrderId: 'LOG-450-01',
    routeLegId: 'RL-450-01',
    elevatorId: 'ELEVATOR-01',
    elevatorName: 'Элеватор Рассказово',
    vehiclePlate: 'А123ВС68',
    trailerPlate: 'В456МР68',
    driverName: 'Иван Соколов',
    status: 'quality_ready',
    queueNumber: 7,
    grossWeightTons: 252.8,
    tareWeightTons: 14.1,
    netWeightTons: 238.7,
    sampleChainId: 'SAMPLE-450-01',
    labProtocolId: 'LAB-SBX-777',
    weightBalanceId: 'WB-450-01',
    qualityDeltaId: 'QD-450-01',
    sdizGateIds: ['SDIZ-TRANSPORT-01'],
    createdAt: now,
    updatedAt: now,
  },
];

export const evidencePacks: EvidencePack[] = [
  {
    id: 'EVP-450-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    documentIds: documents.map((doc) => doc.id),
    weightEvidenceIds: ['PHOTO-WEIGHT-01'],
    photoIds: ['PHOTO-SEAL-01', 'PHOTO-SAMPLE-01', 'PHOTO-LOAD-01'],
    routeEventIds: ['FIELD-ARRIVED-01', 'FIELD-UNLOADED-01'],
    labProtocolIds: ['LAB-SBX-777'],
    sampleChainIds: ['SAMPLE-450-01'],
    supportMessageIds: ['SUP-MSG-01'],
    decisionIds: [],
    createdAt: now,
    updatedAt: now,
  },
];

export const disputes: Dispute[] = [
  {
    id: 'DSP-450-01',
    dealId: 'DL-GRAIN-450',
    batchId: 'GB-450-TMB-01',
    logisticsOrderId: 'LOG-450-01',
    reason: 'quality',
    status: 'open',
    disputedAmount: money(203000),
    undisputedAmount: money(3355466),
    openedByRole: 'buyer',
    openedByPartyId: 'BUYER-01',
    evidencePackId: 'EVP-450-01',
    createdAt: now,
    updatedAt: now,
  },
];
