apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grainflow-ingress
  namespace: grainflow-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.grainflow.ru
        - api.grainflow.ru
      secretName: grainflow-tls
  rules:
    - host: app.grainflow.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grainflow-web
                port:
                  number: 3000
    - host: api.grainflow.ru
      http:
        paths:
          - path: /api/ml/
            pathType: Prefix
            backend:
              service:
                name: grainflow-ml
                port:
                  number: 8001
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grainflow-api
                port:
                  number: 80
