import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const webRoot = existsSync(join(process.cwd(), 'app/platform-v7')) ? process.cwd() : join(process.cwd(), 'apps/web');

const read = (relativePath: string) => readFileSync(join(webRoot, relativePath), 'utf8');

const guardedFiles = [
  'app/platform-v7/bank/escrow/page.tsx',
  'app/platform-v7/bank/events/page.tsx',
  'app/platform-v7/bank/factoring/page.tsx',
  'app/platform-v7/bank/grain/page.tsx',
  'app/platform-v7/bank/release-safety/page.tsx',
  'app/platform-v7/anti-bypass/grain/page.tsx',
  'app/platform-v7/buyer/page.tsx',
  'app/platform-v7/connectors/page.tsx',
  'app/platform-v7/deals/[id]/documents/page.tsx',
  'app/platform-v7/deals/[id]/evidence-pack/page.tsx',
  'app/platform-v7/deals/[id]/transport-documents/page.tsx',
  'app/platform-v7/documents/page.tsx',
  'app/platform-v7/elevator/page.tsx',
  'app/platform-v7/money/page.tsx',
  'app/platform-v7/operator/grain/page.tsx',
  'app/platform-v7/privacy/page.tsx',
  'app/platform-v7/reports/regulator/page.tsx',
  'app/platform-v7/reports/grain/page.tsx',
  'app/platform-v7/runtime-status/page.tsx',
  'app/platform-v7/seller/page.tsx',
  'app/platform-v7/settlement/grain/page.tsx',
  'app/platform-v7/terms/page.tsx',
  'components/platform-v7/AuditSurfaceSummary.tsx',
  'components/platform-v7/BankSmartContractsPanel.tsx',
  'components/platform-v7/DecisionPackMiniPanel.tsx',
  'components/platform-v7/DecisionRecommendationStrip.tsx',
  'components/platform-v7/DocumentReadinessMiniMatrix.tsx',
  'components/platform-v7/DocumentsMatrixActions.tsx',
  'components/platform-v7/DocumentsMatrix.tsx',
  'components/platform-v7/EvidenceReadinessMiniMatrix.tsx',
  'components/platform-v7/P7ActionFeedbackStrip.tsx',
  'components/platform-v7/P7DealWorkspaceTabs.tsx',
  'components/platform-v7/P7EvidenceReadinessAuditStrip.tsx',
  'components/platform-v7/P7EvidenceProjectionPanel.tsx',
  'components/platform-v7/P7MoneySafetyAuditStrip.tsx',
  'components/platform-v7/P7PersistenceQueueStatus.tsx',
  'components/platform-v7/TestModeSystemsPanel.tsx',
  'components/platform-v7/premium/ExecutionUi.tsx',
  'components/v7r/BankRuntime.tsx',
  'components/v7r/ControlTowerOperatorPanel.tsx',
  'components/v7r/DealDetailRuntime.tsx',
  'components/v7r/DealDraftDetailRuntime.tsx',
  'components/v7r/DealDraftDetailRuntimeV2.tsx',
  'components/v7r/DealEvidencePackPreview.tsx',
  'components/v7r/DocumentsDropzone.tsx',
  'components/v7r/DomainControlTowerSummary.tsx',
  'components/v7r/DomainDealsSummary.tsx',
  'components/v7r/DomainMoneySummary.tsx',
  'components/v7r/ExecutionSimulationActionPanel.tsx',
  'components/v7r/LiveDealDetailRuntime.tsx',
  'components/v7r/LiveDealInvestorRuntime.tsx',
  'components/v7r/PlatformCommandCenterHub.tsx',
  'components/v7r/PlatformRolesHub.tsx',
  'components/v7r/RoleContinuityPanel.tsx',
  'components/v7r/RoleEntry.tsx',
  'lib/platform-v7/action-feedback.ts',
  'lib/platform-v7/deal-workspace-actions.ts',
  'lib/platform-v7/deal-workspace-release-readiness.ts',
  'lib/platform-v7/domain/money.ts',
  'lib/platform-v7/execution-command-contracts.ts',
  'lib/platform-v7/integrations/providerRegistry.ts',
  'lib/platform-v7/logistics-receiving-gate.ts',
  'lib/platform-v7/operator-execution-queue.ts',
];

const forbiddenVisibleCopy = [
  'тестовый контур',
  'пилотный контур',
  'тестовый сценарий',
  'Пилотный банковый модуль',
  'Тестовый лимит',
  'Симуляция ответов',
  'controlled pilot',
  'Controlled pilot',
  'Persistence queue status',
  'Evidence projection',
  'Append-only',
  'idempotent',
  'Manual reconciliation',
  'Timeline events',
  'Evidence score',
  'Projected timeline',
  'Журнал evidence',
  'демонстрационная модель',
  'выпуск денег',
  'выпуска денег',
  'Запрос на выпуск денег',
  'Action feedback',
  'Evidence readiness audit',
  'Evidence pack preview',
  'deal-level evidence pack',
  'preview-маршрут',
  'Blocker-docs',
  'Запросить выпуск',
  'Выпустить деньги',
  'Деньги выпущены',
  'blockers cleared',
  'data-demo="true"',
  'Демо-данные',
  'Audit trail',
  'mobile-flow',
  'webhooks',
  'simulation-grade',
  'live-integrated',
  'fully live',
  'production-ready',
  'демо-контур',
  'демо-контура',
  'демо-контуре',
];

describe('platform-v7 deep bank and deal copy guard', () => {
  it('keeps deep bank, deal and evidence surfaces on execution-contour wording', () => {
    const source = guardedFiles.map(read).join('\n');

    for (const copy of forbiddenVisibleCopy) {
      expect(source, `deep platform-v7 copy must not contain "${copy}"`).not.toContain(copy);
    }
  });
});
