import{connect}from'cloudflare:sockets';const U='9c5dfde7-0af0-4c71-b835-8aad0ff33e83';let L=[];const ts=()=>new Date().toISOString().slice(11,19);const log=s=>{L=[ts()+' '+s,...L.slice(0,29)];};

// Extract SNI hostname from TLS ClientHello for better Cloudflare-edge routing
function getSNI(d){try{if(d.length<43||d[0]!==0x16||d[5]!==0x01)return null;let o=43+1+d[43];if(o+2>d.length)return null;o+=2+((d[o]<<8)|d[o+1]);if(o+1>d.length)return null;o+=1+d[o];if(o+2>d.length)return null;const extEnd=o+2+((d[o]<<8)|d[o+1]);o+=2;while(o+4<=extEnd&&o+4<=d.length){const t=(d[o]<<8)|d[o+1],l=(d[o+2]<<8)|d[o+3];o+=4;if(t===0&&l>=5&&d[o+2]===0){const nl=(d[o+3]<<8)|d[o+4];if(nl>0&&o+5+nl<=d.length)return new TextDecoder().decode(d.slice(o+5,o+5+nl));}o+=l;}}catch(e){}return null;}

// Remove DNS HTTPS records (type 65) to block HTTP/3 QUIC discovery -> force TCP
function stripHTTPS(buf){try{if(buf.length<12)return buf;const an=(buf[6]<<8)|buf[7],ns=(buf[8]<<8)|buf[9],ar=(buf[10]<<8)|buf[11];if(an+ns+ar===0)return buf;let p=12;const qd=(buf[4]<<8)|buf[5];for(let i=0;i<qd&&p<buf.length;i++){while(p<buf.length){const l=buf[p];if(!l){p++;break;}if((l&0xC0)===0xC0){p+=2;break;}p+=1+l;}p+=4;}const base=p;let kAn=0,kNs=0,kAr=0,changed=false;const segs=[];for(const[cnt,ia,ib] of [[an,1,0],[ns,0,1],[ar,0,0]]){let k=0;for(let i=0;i<cnt&&p<buf.length;i++){const s=p;while(p<buf.length){const l=buf[p];if(!l){p++;break;}if((l&0xC0)===0xC0){p+=2;break;}p+=1+l;}if(p+10>buf.length)break;const t=(buf[p]<<8)|buf[p+1];p+=10+((buf[p+8]<<8)|buf[p+9]);if(t!==65){segs.push(buf.slice(s,p));k++;}else changed=true;}if(ia)kAn=k;else if(ib)kNs=k;else kAr=k;}if(!changed)return buf;const hdr=buf.slice(0,base);hdr[6]=(kAn>>8)&0xff;hdr[7]=kAn&0xff;hdr[8]=(kNs>>8)&0xff;hdr[9]=kNs&0xff;hdr[10]=(kAr>>8)&0xff;hdr[11]=kAr&0xff;const all=[hdr,...segs];const out=new Uint8Array(all.reduce((s,a)=>s+a.length,0));let off=0;for(const a of all){out.set(a,off);off+=a.length;}return out;}catch(e){return buf;}}

async function handleDNS(ws,v){let q=v.p;if(!q.byteLength){const raw=await new Promise((ok,no)=>{ws.addEventListener('message',e=>ok(e.data),{once:true});ws.addEventListener('close',no,{once:true})});const buf=raw instanceof ArrayBuffer?raw:await raw.arrayBuffer();const b=new Uint8Array(buf);q=b.length>2?b.slice(2):b;}log('DNS '+q.byteLength+'b');try{const r=await fetch('https://cloudflare-dns.com/dns-query',{method:'POST',headers:{'Content-Type':'application/dns-message','Accept':'application/dns-message'},body:q,signal:AbortSignal.timeout(5000)});const raw=new Uint8Array(await r.arrayBuffer());const dns=stripHTTPS(raw);if(dns.length!==raw.length)log('DNS_STRIP');ws.send(new Uint8Array([v.ver,0]).buffer);const out=new Uint8Array(2+dns.length);out[0]=(dns.length>>8)&0xff;out[1]=dns.length&0xff;out.set(dns,2);ws.send(out.buffer);log('DNS_OK '+dns.length+'b');}catch(e){log('DNS_ERR '+e?.message);}try{ws.close()}catch(e){}}

export default{async fetch(req){const path=new URL(req.url).pathname;if(path==='/logs')return new Response(L.join('\n')||'empty',{headers:{'content-type':'text/plain'}});if(path==='/check'){const r=[];try{const res=await fetch('https://example.com',{signal:AbortSignal.timeout(5000)});r.push('fetch:'+res.status);}catch(e){r.push('fetch:ERR '+e?.message?.slice(0,40));}const tests=[['google.com','google.com',443],['youtube.com','youtube.com',443],['googleapis','www.googleapis.com',443],['ytimg','i.ytimg.com',443],['googlevideo','googlevideo.com',443],['instagram','instagram.com',443],['yandex','yandex.ru',443],['google_ip','142.250.185.46',443],['fb_ip','157.240.241.35',443],['example_ip','93.184.216.34',443]];await Promise.all(tests.map(async([lbl,h,p])=>{const t0=Date.now();let tc;try{tc=connect({hostname:h,port:p});await Promise.race([tc.opened,new Promise((_,rej)=>setTimeout(()=>rej(new Error('5s')),5000))]);r.push(lbl+':ok_'+(Date.now()-t0)+'ms');}catch(e){r.push(lbl+':FAIL_'+(Date.now()-t0)+'ms_'+e?.message?.slice(0,50));}finally{try{if(tc)tc.close()}catch(x){}}}));return new Response(r.join('\n'),{headers:{'content-type':'text/plain'}});}if(req.headers.get('Upgrade')!=='websocket')return new Response('vless-proxy v9 ok');const[c,s]=Object.values(new WebSocketPair());s.accept();vless(s).catch(e=>{if(e?.message&&!e.message.includes('cancel'))log('ERR:'+e.message?.slice(0,80));try{s.close()}catch(x){}});return new Response(null,{status:101,webSocket:c});}};

async function vless(ws){const raw=await new Promise((ok,no)=>{ws.addEventListener('message',e=>ok(e.data),{once:true});ws.addEventListener('close',no,{once:true})});const buf=raw instanceof ArrayBuffer?raw:await raw.arrayBuffer();const bytes=new Uint8Array(buf);const v=parse(bytes,U);if(!v){const al=bytes[17]||0;const cmd=bytes[18+al];log('FAIL cmd='+cmd+' len='+buf.byteLength);ws.close();return;}if(v.cmd===2){if(v.port===53)await handleDNS(ws,v);else{log('QUIC '+v.host+':'+v.port);ws.close();}return;}
// Cloudflare's own DoH IPs can't be proxied via cloudflare:sockets (policy block)
// Reject immediately so client falls back to UDP DNS (which we handle in handleDNS)
if((v.host==='1.1.1.1'||v.host==='1.0.0.1')&&v.port===443){log('REJECT CF-DoH');ws.close();return;}
let dest=v.host;if(dest==='1.1.1.1'||dest==='1.0.0.1')dest='8.8.8.8';
let connectTo=dest;
// Only apply SNI extraction if we didn't already redirect the destination
// (if we did, the SNI might reference a Cloudflare-blocked hostname)
const isIP=/^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(dest)||dest.includes(':');
if(v.port===443&&isIP&&dest===v.host&&v.p.byteLength>0){const sni=getSNI(v.p);if(sni){log('SNI '+dest+'->'+sni);connectTo=sni;}}
log('TRY '+v.host+(dest!==v.host?'->'+dest:'')+(connectTo!==dest?' via:'+connectTo:'')+':'+v.port);
let tcp;try{tcp=connect({hostname:connectTo,port:v.port});await Promise.race([tcp.opened,new Promise((_,rej)=>setTimeout(()=>rej(new Error('connect_timeout')),8000))]);log('CON '+connectTo+':'+v.port);const wr=tcp.writable.getWriter();if(v.p.byteLength>0)await wr.write(v.p);ws.send(new Uint8Array([v.ver,0]).buffer);const ac=new AbortController();let done=false;const shut=()=>{if(done)return;done=true;ac.abort();try{ws.close()}catch(x){}try{tcp.close()}catch(x){}};let q=Promise.resolve();ws.addEventListener('message',e=>{q=q.then(async()=>{if(done)return;try{const d=e.data instanceof ArrayBuffer?e.data:await e.data.arrayBuffer();await wr.write(new Uint8Array(d))}catch(x){shut();}})});ws.addEventListener('close',()=>{try{wr.releaseLock()}catch(x){}shut();});await tcp.readable.pipeTo(new WritableStream({write(chunk){ws.send(chunk);},close(){shut();},abort(e){if(e?.message&&!e.message.includes('cancel')&&!e.message.includes('abort'))log('PIPE '+connectTo+':'+v.port+' '+e?.message?.slice(0,50));shut();}}),{signal:ac.signal}).catch(e=>{if(e?.message&&!e.message.includes('cancel')&&!e.message.includes('abort'))log('PIPE2 '+connectTo+' '+e?.message?.slice(0,50));shut();});}catch(e){if(e?.message&&!e.message.includes('cancel'))log('ERR '+connectTo+':'+v.port+' '+e.message?.slice(0,60));try{if(tcp)tcp.close()}catch(x){}try{ws.close()}catch(x){}}}

function parse(a,uid){if(a.length<24)return null;const u=Array.from(a.slice(1,17),b=>b.toString(16).padStart(2,'0')).join('').replace(/(.{8})(.{4})(.{4})(.{4})/,'$1-$2-$3-$4-');if(u!==uid)return null;const al=a[17],o=18+al;const cmd=a[o];if(cmd!==1&&cmd!==2)return null;const port=(a[o+1]<<8)|a[o+2],at=a[o+3];let host,end;if(at===1){host=a.slice(o+4,o+8).join('.');end=o+8;}else if(at===2){const l=a[o+4];host=new TextDecoder().decode(a.slice(o+5,o+5+l));end=o+5+l;}else if(at===3){const dv=new DataView(a.buffer,a.byteOffset+o+4,16);host=Array.from({length:8},(_,i)=>dv.getUint16(i*2).toString(16)).join(':');end=o+20;}else return null;return{ver:a[0],host,port,cmd,p:new Uint8Array(a.buffer.slice(a.byteOffset+end))};}
