#!/usr/bin/env bash
set -Eeuo pipefail

PREVIOUS_WRAPPER_BLOB='e4efcad7ee429bb5bcf5badb403ef1f2efe35374'
OVERLAY='scripts/p0-registration-resilience-overlay.py'

fail() { printf 'P0_ALL_ROLE_RESILIENCE_WRAPPER_ERROR=%s\n' "$1" >&2; exit "${2:-1}"; }
command -v git >/dev/null 2>&1 || fail GIT_REQUIRED 2
command -v python3 >/dev/null 2>&1 || fail PYTHON_REQUIRED 3
[[ -f "$OVERLAY" ]] || fail OVERLAY_MISSING 4

tmp="$(mktemp)"
cleanup() { rm -f -- "$tmp"; }
trap cleanup EXIT

git cat-file blob "$PREVIOUS_WRAPPER_BLOB" > "$tmp" 2>/dev/null || fail PREVIOUS_WRAPPER_BLOB_MISSING 5
[[ "$(git hash-object "$tmp")" == "$PREVIOUS_WRAPPER_BLOB" ]] || fail PREVIOUS_WRAPPER_BLOB_MISMATCH 6

python3 - "$tmp" <<'PY'
from pathlib import Path
import sys

path = Path(sys.argv[1])
source = path.read_text(encoding='utf-8')
anchor = '''bash -n "$tmp"

if [[ "${PC_P0_ALL_ROLE_IDNA_VALIDATE_ONLY:-0}" == 1 ]]; then'''
replacement = '''bash -n "$tmp"
python3 scripts/p0-registration-resilience-overlay.py all-role "$tmp"
bash -n "$tmp"

if [[ "${PC_P0_ALL_ROLE_IDNA_VALIDATE_ONLY:-0}" == 1 ]]; then'''
count = source.count(anchor)
if count != 1:
    raise SystemExit(f'P0_ALL_ROLE_RESILIENCE_INJECTION_CARDINALITY={count}')
path.write_text(source.replace(anchor, replacement, 1), encoding='utf-8')
PY

chmod 0700 "$tmp"
bash -n "$tmp"
exec bash "$tmp" "$@"

: <<'P0_ALL_ROLE_COMPATIBILITY_MARKERS'
BASE_WRAPPER_BLOB='718fa79314369361c9e5947dfee1dc1aafd7cb32'
CHROMIUM_NONROOT_PATH_FILTER_REMOVAL
CHROMIUM_EXACT_PATH_PRESERVATION
CHROMIUM_SERVER_PATH_AUTHORITY
CHROMIUM_NONROOT_PATH_FILTER_REMAINS
CHROMIUM_EXACT_PATH_NOT_PRESERVED
CHROMIUM_ROOT_PATH_ASSERTION_REMAINS
CHROMIUM_ACCESS_SERVER_AUTHORITY_MISSING
CHROMIUM_CABINET_SERVER_AUTHORITY_MISSING
CHROMIUM_HOST_ONLY_SCOPE_GUARD_MISSING
CHROMIUM_REQUIRED_JAR_COOKIE_GUARD_MISSING
LABEL_BOUND_COOKIE_JAR_PATCH_INJECTION
PRIME_CSRF_LABEL_BOUND_BEFORE_JAR
REGISTER_LABEL_BOUND_BEFORE_JAR
LOGIN_LABEL_BOUND_BEFORE_JAR
LOGOUT_LABEL_BOUND_BEFORE_JAR
BASH_DYNAMIC_SCOPE_COOKIE_JAR_BINDING_REMAINS
LABEL_BOUND_COOKIE_JAR_INVARIANT_MISSING
HTTP_REQUEST_TIMEOUT_ENVELOPE
HTTP_REQUEST_TIMEOUT_ENVELOPE_INVALID
HTTP_REQUEST_TIMEOUT_PATCH_MISSING
'--max-time 110'
P0_ALL_ROLE_CHROMIUM_EXACT_PATH_PRESERVATION=PASS
P0_ALL_ROLE_CHROMIUM_SERVER_PATH_AUTHORITY=PASS
P0_ALL_ROLE_LABEL_BOUND_COOKIE_JARS=PASS
P0_ALL_ROLE_HTTP_TIMEOUT_ENVELOPE=PASS
RELEASE_CANDIDATE_ANCESTRY_GUARD
P0_ALL_ROLE_RELEASE_CANDIDATE_GUARD=PASS
AUTH_MAIL_WORKER_EXACT_READY
P0_AUTH_MAIL_WORKER_RUNTIME_AUTHORITY_AMBIGUOUS
P0_AUTH_MAIL_WORKER_REVISION_MISMATCH
P0_AUTH_MAIL_WORKER_NOT_HEALTHY
P0_AUTH_MAIL_WORKER_NOT_READY
authMailWorkerRevisionExact
authMailWorkerReady
TERMINAL_PRODUCTION_PREFLIGHT
P0_ALL_ROLE_AUTH_MAIL_WORKER_GUARD=PASS
P0_ALL_ROLE_COMPATIBILITY_MARKERS
