-- Historical compatibility migration.
--
-- This migration was originally generated for the retired SQLite datasource.
-- It recreates deals, shipments, checkpoints, deal_documents, payments,
-- lab_samples, lab_tests and their indexes using SQLite DATETIME/REAL/TEXT
-- storage. All of those canonical PostgreSQL tables and indexes are already
-- created by the preceding `0001_postgresql_initial` migration with TIMESTAMPTZ,
-- DOUBLE PRECISION, BIGINT and JSONB types.
--
-- The directory and migration identifier are intentionally preserved so Prisma's
-- ordered migration history remains deterministic. Applying the legacy DDL would
-- either fail on SQLite-only types or attempt to recreate existing relations.
-- Deleting the migration or marking it resolved outside version control is not an
-- acceptable production migration strategy.
SELECT 1;
