-- PC-CROP federal accounting, Wave 2 fifth slice: the documents themselves.
--
-- Until now the staleness rule had nothing to be true about. This migration
-- gives it storage: a document, and an immutable row per rendering of it that
-- records the revisions it was generated from.
--
-- Why not extend `deal_documents`, which already has a type, a hash and a
-- signedAt? Three reasons, in ascending order of seriousness:
--
--   1. It stores an uploaded file. The accounting document is generated by the
--      platform from its own data, so it can be regenerated and compared; a
--      file cannot.
--   2. Its `version` is a counter on a single row, so an earlier rendering's
--      bytes are gone. A signature is evidence of what was signed, which
--      requires the superseded content to still exist.
--   3. Its tenant column defaults to `current_setting('app.current_tenant_id')`
--      — the tenant is whatever the caller last said it was. The identity
--      contour measured that exact failure, and adding accounting rows to that
--      table would inherit it.
--
-- `deal_documents` is untouched: it keeps holding the files, and a later slice
-- may point one at the accounting version it was rendered from.
--
-- The invariant this migration exists to establish is that a signature is a
-- one-way door and the bytes underneath it cannot move afterwards. It is
-- enforced three times over, because each mechanism binds a different set of
-- principals:
--
--   * a column grant, which stops the confined runtime from writing the hash
--     or the revision snapshot at all;
--   * a row level policy, which only admits an UPDATE of an unsigned row;
--   * a trigger, which binds everyone including the superuser and any future
--     principal that has not been thought about yet.
--
-- The trigger is the one that survives a mistake. A migration that genuinely
-- needs to rewrite signed history must disable it by name, which is a visible
-- act in a reviewed diff rather than an accident.

-- CreateTable
CREATE TABLE "accounting_documents" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "documentType" TEXT NOT NULL,
    "documentNumber" TEXT,
    "dealId" TEXT,
    "counterpartyOrgId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "currentVersionNumber" INTEGER NOT NULL DEFAULT 0,
    "createdByMembershipId" TEXT NOT NULL,
    "version" BIGINT NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "accounting_documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "accounting_document_versions" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "documentId" TEXT NOT NULL,
    "versionNumber" INTEGER NOT NULL,
    "payloadHash" TEXT NOT NULL,
    "recordedRevisions" JSONB NOT NULL,
    "totalKopecks" BIGINT,
    "signedAt" TIMESTAMPTZ(6),
    "signedByMembershipId" TEXT,
    "signingAuthorityId" TEXT,
    "signatureCertificateFingerprint" TEXT,
    "createdByMembershipId" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "accounting_document_versions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "accounting_documents_organizationId_status_documentType_idx" ON "accounting_documents"("organizationId", "status", "documentType");

-- CreateIndex
CREATE INDEX "accounting_documents_tenantId_idx" ON "accounting_documents"("tenantId");

-- CreateIndex
CREATE INDEX "accounting_documents_dealId_idx" ON "accounting_documents"("dealId");

-- CreateIndex
CREATE UNIQUE INDEX "accounting_documents_number_identity_idx" ON "accounting_documents"("organizationId", "documentType", "documentNumber");

-- CreateIndex
CREATE INDEX "accounting_document_versions_organizationId_documentId_idx" ON "accounting_document_versions"("organizationId", "documentId");

-- CreateIndex
CREATE INDEX "accounting_document_versions_tenantId_idx" ON "accounting_document_versions"("tenantId");

-- CreateIndex
CREATE UNIQUE INDEX "accounting_document_versions_documentId_versionNumber_key" ON "accounting_document_versions"("documentId", "versionNumber");

-- AddForeignKey
ALTER TABLE "accounting_documents" ADD CONSTRAINT "accounting_documents_organizationId_tenantId_fkey" FOREIGN KEY ("organizationId", "tenantId") REFERENCES "organizations"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounting_documents" ADD CONSTRAINT "accounting_documents_createdByMembershipId_organizationId_fkey" FOREIGN KEY ("createdByMembershipId", "organizationId") REFERENCES "user_orgs"("id", "organizationId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounting_document_versions" ADD CONSTRAINT "accounting_document_versions_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "accounting_documents"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounting_document_versions" ADD CONSTRAINT "accounting_document_versions_organizationId_tenantId_fkey" FOREIGN KEY ("organizationId", "tenantId") REFERENCES "organizations"("id", "tenantId") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounting_document_versions" ADD CONSTRAINT "accounting_document_versions_createdByMembershipId_organiz_fkey" FOREIGN KEY ("createdByMembershipId", "organizationId") REFERENCES "user_orgs"("id", "organizationId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounting_document_versions" ADD CONSTRAINT "accounting_document_versions_signedByMembershipId_organiza_fkey" FOREIGN KEY ("signedByMembershipId", "organizationId") REFERENCES "user_orgs"("id", "organizationId") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "accounting_document_versions" ADD CONSTRAINT "accounting_document_versions_signingAuthorityId_fkey" FOREIGN KEY ("signingAuthorityId") REFERENCES "signing_authorities"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Constraints ---------------------------------------------------------------

ALTER TABLE public."accounting_documents"
  DROP CONSTRAINT IF EXISTS accounting_documents_status_check;
ALTER TABLE public."accounting_documents"
  ADD CONSTRAINT accounting_documents_status_check
  CHECK ("status" IN ('DRAFT', 'ISSUED', 'CANCELLED'));

-- An issued document without a number cannot be referred to by a counterparty,
-- a tax authority or an operator. Refusing it here means the numbering policy
-- can never be skipped, including by a caller that has not been written yet.
ALTER TABLE public."accounting_documents"
  DROP CONSTRAINT IF EXISTS accounting_documents_issued_number_check;
ALTER TABLE public."accounting_documents"
  ADD CONSTRAINT accounting_documents_issued_number_check
  CHECK ("status" = 'DRAFT' OR "documentNumber" IS NOT NULL);

ALTER TABLE public."accounting_documents"
  DROP CONSTRAINT IF EXISTS accounting_documents_number_not_blank_check;
ALTER TABLE public."accounting_documents"
  ADD CONSTRAINT accounting_documents_number_not_blank_check
  CHECK ("documentNumber" IS NULL OR length(btrim("documentNumber")) > 0);

ALTER TABLE public."accounting_documents"
  DROP CONSTRAINT IF EXISTS accounting_documents_current_version_check;
ALTER TABLE public."accounting_documents"
  ADD CONSTRAINT accounting_documents_current_version_check
  CHECK ("currentVersionNumber" >= 0);

ALTER TABLE public."accounting_document_versions"
  DROP CONSTRAINT IF EXISTS accounting_document_versions_number_check;
ALTER TABLE public."accounting_document_versions"
  ADD CONSTRAINT accounting_document_versions_number_check
  CHECK ("versionNumber" > 0);

ALTER TABLE public."accounting_document_versions"
  DROP CONSTRAINT IF EXISTS accounting_document_versions_payload_hash_check;
ALTER TABLE public."accounting_document_versions"
  ADD CONSTRAINT accounting_document_versions_payload_hash_check
  CHECK (length(btrim("payloadHash")) > 0);

-- The snapshot is the mechanism. An array or a bare string here would make
-- every lookup miss and quietly turn every version unverifiable.
ALTER TABLE public."accounting_document_versions"
  DROP CONSTRAINT IF EXISTS accounting_document_versions_revisions_object_check;
ALTER TABLE public."accounting_document_versions"
  ADD CONSTRAINT accounting_document_versions_revisions_object_check
  CHECK (jsonb_typeof("recordedRevisions") = 'object');

-- A signature is four facts or none of them. Half a signature — a timestamp
-- with no signer, a certificate with no authority — would read as signed to
-- anything that only checks signedAt.
ALTER TABLE public."accounting_document_versions"
  DROP CONSTRAINT IF EXISTS accounting_document_versions_signature_complete_check;
ALTER TABLE public."accounting_document_versions"
  ADD CONSTRAINT accounting_document_versions_signature_complete_check
  CHECK (
    num_nonnulls(
      "signedAt",
      "signedByMembershipId",
      "signingAuthorityId",
      "signatureCertificateFingerprint"
    ) IN (0, 4)
  );

-- Immutability -------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.pc_crop_accounting_version_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- The parent decides the tenancy. Without this a version could claim an
    -- organization of its own choosing while hanging off somebody else's
    -- document, and the row would still satisfy every foreign key.
    IF NOT EXISTS (
      SELECT 1
      FROM public."accounting_documents" parent
      WHERE parent."id" = NEW."documentId"
        AND parent."organizationId" = NEW."organizationId"
        AND parent."tenantId" = NEW."tenantId"
    ) THEN
      RAISE EXCEPTION
        'accounting document version must belong to its document''s organization and tenant';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD."signedAt" IS NOT NULL THEN
    RAISE EXCEPTION 'a signed accounting document version is immutable';
  END IF;
  IF NEW."payloadHash" IS DISTINCT FROM OLD."payloadHash" THEN
    RAISE EXCEPTION 'the payload hash of an accounting document version never changes';
  END IF;
  IF NEW."recordedRevisions" IS DISTINCT FROM OLD."recordedRevisions" THEN
    RAISE EXCEPTION 'the recorded source revisions of an accounting document version never change';
  END IF;
  IF NEW."versionNumber" IS DISTINCT FROM OLD."versionNumber" THEN
    RAISE EXCEPTION 'the number of an accounting document version never changes';
  END IF;
  IF NEW."documentId" IS DISTINCT FROM OLD."documentId" THEN
    RAISE EXCEPTION 'an accounting document version never moves to another document';
  END IF;

  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS accounting_document_versions_guard
  ON public."accounting_document_versions";
CREATE TRIGGER accounting_document_versions_guard
  BEFORE INSERT OR UPDATE ON public."accounting_document_versions"
  FOR EACH ROW EXECUTE FUNCTION public.pc_crop_accounting_version_guard();

CREATE OR REPLACE FUNCTION public.pc_crop_accounting_document_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
  IF OLD."documentNumber" IS NOT NULL
     AND NEW."documentNumber" IS DISTINCT FROM OLD."documentNumber" THEN
    RAISE EXCEPTION 'an issued document number is never reassigned';
  END IF;
  IF NEW."documentType" IS DISTINCT FROM OLD."documentType" THEN
    RAISE EXCEPTION 'the type of an accounting document never changes';
  END IF;
  IF NEW."organizationId" IS DISTINCT FROM OLD."organizationId"
     OR NEW."tenantId" IS DISTINCT FROM OLD."tenantId" THEN
    RAISE EXCEPTION 'an accounting document never moves to another organization';
  END IF;
  -- Versions only ever accumulate, so the pointer to the newest one only ever
  -- goes forward. Letting it go back would hide renderings that exist.
  IF NEW."currentVersionNumber" < OLD."currentVersionNumber" THEN
    RAISE EXCEPTION 'the current version of an accounting document never goes backwards';
  END IF;

  RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS accounting_documents_guard
  ON public."accounting_documents";
CREATE TRIGGER accounting_documents_guard
  BEFORE UPDATE ON public."accounting_documents"
  FOR EACH ROW EXECUTE FUNCTION public.pc_crop_accounting_document_guard();

-- Row level security --------------------------------------------------------

ALTER TABLE public."accounting_documents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."accounting_documents" FORCE ROW LEVEL SECURITY;
ALTER TABLE public."accounting_document_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."accounting_document_versions" FORCE ROW LEVEL SECURITY;

-- Reading, on the same terms as the rest of this contour: the request setting
-- picks a candidate set and app_pc_crop_membership_id() decides whether the
-- caller may have it, by reading an ACTIVE membership out of user_orgs rather
-- than believing the setting.
DROP POLICY IF EXISTS accounting_documents_member_select ON public."accounting_documents";
CREATE POLICY accounting_documents_member_select ON public."accounting_documents"
  FOR SELECT
  USING (
    public.app_pc_crop_membership_id() IS NOT NULL
    AND "organizationId" = public.app_identity_org_id()
    AND "tenantId" = public.app_identity_tenant_id()
  );

DROP POLICY IF EXISTS accounting_document_versions_member_select ON public."accounting_document_versions";
CREATE POLICY accounting_document_versions_member_select ON public."accounting_document_versions"
  FOR SELECT
  USING (
    public.app_pc_crop_membership_id() IS NOT NULL
    AND "organizationId" = public.app_identity_org_id()
    AND "tenantId" = public.app_identity_tenant_id()
  );

DROP POLICY IF EXISTS accounting_documents_command_insert ON public."accounting_documents";
CREATE POLICY accounting_documents_command_insert ON public."accounting_documents"
  FOR INSERT
  WITH CHECK (
    public.app_pc_crop_membership_id() IS NOT NULL
    AND "organizationId" = public.app_identity_org_id()
    AND "tenantId" = public.app_identity_tenant_id()
    AND "createdByMembershipId" = public.app_pc_crop_membership_id()
  );

DROP POLICY IF EXISTS accounting_documents_command_update ON public."accounting_documents";
CREATE POLICY accounting_documents_command_update ON public."accounting_documents"
  FOR UPDATE
  USING (
    public.app_pc_crop_membership_id() IS NOT NULL
    AND "organizationId" = public.app_identity_org_id()
    AND "tenantId" = public.app_identity_tenant_id()
  )
  WITH CHECK (
    "organizationId" = public.app_identity_org_id()
    AND "tenantId" = public.app_identity_tenant_id()
  );

DROP POLICY IF EXISTS accounting_document_versions_command_insert ON public."accounting_document_versions";
CREATE POLICY accounting_document_versions_command_insert ON public."accounting_document_versions"
  FOR INSERT
  WITH CHECK (
    public.app_pc_crop_membership_id() IS NOT NULL
    AND "organizationId" = public.app_identity_org_id()
    AND "tenantId" = public.app_identity_tenant_id()
    AND "createdByMembershipId" = public.app_pc_crop_membership_id()
    -- A version is written unsigned and signed afterwards, so that signing
    -- passes through the update path where the guard and the column grant can
    -- see it. Inserting a pre-signed row would walk around both.
    AND "signedAt" IS NULL
    AND "signedByMembershipId" IS NULL
    AND "signingAuthorityId" IS NULL
    AND "signatureCertificateFingerprint" IS NULL
  );

-- Signing is the only permitted update, and only of a version nobody has
-- signed yet. The trigger says the same thing to every principal; this says it
-- to the confined one before the row is ever read.
DROP POLICY IF EXISTS accounting_document_versions_command_sign ON public."accounting_document_versions";
CREATE POLICY accounting_document_versions_command_sign ON public."accounting_document_versions"
  FOR UPDATE
  USING (
    public.app_pc_crop_membership_id() IS NOT NULL
    AND "organizationId" = public.app_identity_org_id()
    AND "tenantId" = public.app_identity_tenant_id()
    AND "signedAt" IS NULL
  )
  WITH CHECK (
    "organizationId" = public.app_identity_org_id()
    AND "tenantId" = public.app_identity_tenant_id()
  );

-- Privileges ----------------------------------------------------------------

DO $accounting_document_grants$
DECLARE
  read_role text := 'pc_accounting_authority';
  write_role text := 'pc_accounting_command_authority';
BEGIN
  IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = read_role) THEN
    EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', read_role);

    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON public."accounting_documents" FROM %I', read_role);
    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON public."accounting_document_versions" FROM %I', read_role);

    EXECUTE format(
      'GRANT SELECT ON public."accounting_documents" TO %I', read_role);
    EXECUTE format(
      'GRANT SELECT ON public."accounting_document_versions" TO %I', read_role);
  END IF;

  IF EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = write_role) THEN
    EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', write_role);

    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON public."accounting_documents" FROM %I', write_role);
    EXECUTE format(
      'REVOKE ALL PRIVILEGES ON public."accounting_document_versions" FROM %I', write_role);

    EXECUTE format(
      'GRANT INSERT, SELECT ON public."accounting_documents" TO %I', write_role);
    -- Issuing sets the number and the status; adding a version moves the
    -- pointer. Everything else about a document is settled when it is created.
    EXECUTE format(
      'GRANT UPDATE ("status", "documentNumber", "currentVersionNumber", "updatedAt", "version") ON public."accounting_documents" TO %I',
      write_role);

    EXECUTE format(
      'GRANT INSERT, SELECT ON public."accounting_document_versions" TO %I', write_role);
    -- The signature columns and nothing else. The payload hash and the
    -- revision snapshot are not writable after insert by this principal at
    -- all, which is what makes the signature cover a fixed artefact.
    EXECUTE format(
      'GRANT UPDATE ("signedAt", "signedByMembershipId", "signingAuthorityId", "signatureCertificateFingerprint") ON public."accounting_document_versions" TO %I',
      write_role);

    -- A document that was issued and then deleted leaves a hole in a numbered
    -- sequence that an auditor reads as evidence of concealment. Cancellation
    -- is a status.
    EXECUTE format(
      'REVOKE DELETE ON public."accounting_documents" FROM %I', write_role);
    EXECUTE format(
      'REVOKE DELETE ON public."accounting_document_versions" FROM %I', write_role);
  END IF;
END
$accounting_document_grants$;
